# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.credential import Credential
from ...models.error import Error
from ...models.registration_finish_request import RegistrationFinishRequest
from ...types import Response


def _get_kwargs(
    *,
    body: RegistrationFinishRequest,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/auth/register/finish",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Credential | Error | None:
    if response.status_code == 201:
        response_201 = Credential.from_dict(response.json())

        return response_201

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Credential | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: RegistrationFinishRequest,
) -> Response[Credential | Error]:
    """Complete passkey registration

     Verifies the browser's attestation response and stores the new
    credential. The first successful call (no admin account yet)
    creates the account; every later call adds another credential to
    it. Issues a new session either way.

    Args:
        body (RegistrationFinishRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Credential | Error]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: RegistrationFinishRequest,
) -> Credential | Error | None:
    """Complete passkey registration

     Verifies the browser's attestation response and stores the new
    credential. The first successful call (no admin account yet)
    creates the account; every later call adds another credential to
    it. Issues a new session either way.

    Args:
        body (RegistrationFinishRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Credential | Error
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: RegistrationFinishRequest,
) -> Response[Credential | Error]:
    """Complete passkey registration

     Verifies the browser's attestation response and stores the new
    credential. The first successful call (no admin account yet)
    creates the account; every later call adds another credential to
    it. Issues a new session either way.

    Args:
        body (RegistrationFinishRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Credential | Error]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: RegistrationFinishRequest,
) -> Credential | Error | None:
    """Complete passkey registration

     Verifies the browser's attestation response and stores the new
    credential. The first successful call (no admin account yet)
    creates the account; every later call adds another credential to
    it. Issues a new session either way.

    Args:
        body (RegistrationFinishRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Credential | Error
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
        )
    ).parsed
