# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.auth_status import AuthStatus
from ...types import Response


def _get_kwargs() -> dict[str, Any]:

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/auth/status",
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> AuthStatus | None:
    if response.status_code == 200:
        response_200 = AuthStatus.from_dict(response.json())

        return response_200

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[AuthStatus]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
) -> Response[AuthStatus]:
    """Report whether an admin account exists yet

     A read-only, side-effect-free check the login page uses to decide
    whether to offer registering the first passkey or logging in with
    one - no cookie set, no ceremony started. Leaks nothing new:
    `POST /auth/login/begin` already reveals this same boolean today
    via its 400 error body
    (openspec/changes/gate-passkey-registration-ui/design.md).

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AuthStatus]
    """

    kwargs = _get_kwargs()

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
) -> AuthStatus | None:
    """Report whether an admin account exists yet

     A read-only, side-effect-free check the login page uses to decide
    whether to offer registering the first passkey or logging in with
    one - no cookie set, no ceremony started. Leaks nothing new:
    `POST /auth/login/begin` already reveals this same boolean today
    via its 400 error body
    (openspec/changes/gate-passkey-registration-ui/design.md).

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AuthStatus
    """

    return sync_detailed(
        client=client,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
) -> Response[AuthStatus]:
    """Report whether an admin account exists yet

     A read-only, side-effect-free check the login page uses to decide
    whether to offer registering the first passkey or logging in with
    one - no cookie set, no ceremony started. Leaks nothing new:
    `POST /auth/login/begin` already reveals this same boolean today
    via its 400 error body
    (openspec/changes/gate-passkey-registration-ui/design.md).

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[AuthStatus]
    """

    kwargs = _get_kwargs()

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
) -> AuthStatus | None:
    """Report whether an admin account exists yet

     A read-only, side-effect-free check the login page uses to decide
    whether to offer registering the first passkey or logging in with
    one - no cookie set, no ceremony started. Leaks nothing new:
    `POST /auth/login/begin` already reveals this same boolean today
    via its 400 error body
    (openspec/changes/gate-passkey-registration-ui/design.md).

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        AuthStatus
    """

    return (
        await asyncio_detailed(
            client=client,
        )
    ).parsed
