# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.owner_identity import OwnerIdentity
from ...types import Response


def _get_kwargs() -> dict[str, Any]:

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/auth/identity",
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | OwnerIdentity | None:
    if response.status_code == 200:
        response_200 = OwnerIdentity.from_dict(response.json())

        return response_200

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | OwnerIdentity]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
) -> Response[Error | OwnerIdentity]:
    """Report the calling session's escrowed identity public key

     The web UI's create/edit dialog reads this to offer the owner's
    own public key as an additional sealing recipient when the
    owner-recipient opt-in checkbox is checked
    (specs/secret-objects/spec.md's "Opt-in owner-recipient inclusion
    at create time" requirement). Session-gated, unlike
    `GET /auth/status`: an age public key isn't secret on its own, but
    every other endpoint that exposes stored data (`GET /consumers`
    included) stays behind a session or bearer token, and this keeps
    that same posture rather than carving out an exception.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | OwnerIdentity]
    """

    kwargs = _get_kwargs()

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
) -> Error | OwnerIdentity | None:
    """Report the calling session's escrowed identity public key

     The web UI's create/edit dialog reads this to offer the owner's
    own public key as an additional sealing recipient when the
    owner-recipient opt-in checkbox is checked
    (specs/secret-objects/spec.md's "Opt-in owner-recipient inclusion
    at create time" requirement). Session-gated, unlike
    `GET /auth/status`: an age public key isn't secret on its own, but
    every other endpoint that exposes stored data (`GET /consumers`
    included) stays behind a session or bearer token, and this keeps
    that same posture rather than carving out an exception.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | OwnerIdentity
    """

    return sync_detailed(
        client=client,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
) -> Response[Error | OwnerIdentity]:
    """Report the calling session's escrowed identity public key

     The web UI's create/edit dialog reads this to offer the owner's
    own public key as an additional sealing recipient when the
    owner-recipient opt-in checkbox is checked
    (specs/secret-objects/spec.md's "Opt-in owner-recipient inclusion
    at create time" requirement). Session-gated, unlike
    `GET /auth/status`: an age public key isn't secret on its own, but
    every other endpoint that exposes stored data (`GET /consumers`
    included) stays behind a session or bearer token, and this keeps
    that same posture rather than carving out an exception.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | OwnerIdentity]
    """

    kwargs = _get_kwargs()

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
) -> Error | OwnerIdentity | None:
    """Report the calling session's escrowed identity public key

     The web UI's create/edit dialog reads this to offer the owner's
    own public key as an additional sealing recipient when the
    owner-recipient opt-in checkbox is checked
    (specs/secret-objects/spec.md's "Opt-in owner-recipient inclusion
    at create time" requirement). Session-gated, unlike
    `GET /auth/status`: an age public key isn't secret on its own, but
    every other endpoint that exposes stored data (`GET /consumers`
    included) stays behind a session or bearer token, and this keeps
    that same posture rather than carving out an exception.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | OwnerIdentity
    """

    return (
        await asyncio_detailed(
            client=client,
        )
    ).parsed
