# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

if TYPE_CHECKING:
    from ..models.audit_actor_option import AuditActorOption


T = TypeVar("T", bound="AuditLogFilterOptions")


@_attrs_define
class AuditLogFilterOptions:
    """
    Attributes:
        object_ids (list[str]): Every distinct object id currently recorded in the audit log.
        actors (list[AuditActorOption]): Every distinct actor currently recorded in the audit log.
        callers (list[str]): Every distinct caller currently recorded in the audit log.
    """

    object_ids: list[str]
    actors: list[AuditActorOption]
    callers: list[str]
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        object_ids = self.object_ids

        actors = []
        for actors_item_data in self.actors:
            actors_item = actors_item_data.to_dict()
            actors.append(actors_item)

        callers = self.callers

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "object_ids": object_ids,
                "actors": actors,
                "callers": callers,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.audit_actor_option import AuditActorOption  # noqa: PLC0415

        d = dict(src_dict)
        object_ids = cast(list[str], d.pop("object_ids"))

        actors = []
        _actors = d.pop("actors")
        for actors_item_data in _actors:
            actors_item = AuditActorOption.from_dict(actors_item_data)

            actors.append(actors_item)

        callers = cast(list[str], d.pop("callers"))

        audit_log_filter_options = cls(
            object_ids=object_ids,
            actors=actors,
            callers=callers,
        )

        audit_log_filter_options.additional_properties = d
        return audit_log_filter_options

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
