# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.audit_log_entry_action import AuditLogEntryAction
from ..models.audit_log_entry_actor_type import AuditLogEntryActorType
from ..types import UNSET, Unset

T = TypeVar("T", bound="AuditLogEntry")


@_attrs_define
class AuditLogEntry:
    """
    Attributes:
        object_id (str):
        action (AuditLogEntryAction):
        timestamp (datetime.datetime):
        ip (str): The request's source IP. Unlike caller, this is never
            self-reported - it's the one piece of the request nobody gets
            to lie about via a header. Currently the immediate TCP peer's
            address; this service isn't deployed behind a reverse proxy or
            load balancer, so X-Forwarded-For (or similar) support isn't
            implemented yet.
        caller (str | Unset): The caller's presented identity, if any.
        actor_type (AuditLogEntryActorType | Unset): The kind of verified credential that authenticated this call -
            absent for an unauthenticated read. Unlike caller, this is
            never self-reported.
        actor_id (str | Unset): The specific token id or admin account this call was
            authenticated as - absent for an unauthenticated read.
    """

    object_id: str
    action: AuditLogEntryAction
    timestamp: datetime.datetime
    ip: str
    caller: str | Unset = UNSET
    actor_type: AuditLogEntryActorType | Unset = UNSET
    actor_id: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        object_id = self.object_id

        action = self.action.value

        timestamp = self.timestamp.isoformat()

        ip = self.ip

        caller = self.caller

        actor_type: str | Unset = UNSET
        if not isinstance(self.actor_type, Unset):
            actor_type = self.actor_type.value

        actor_id = self.actor_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "object_id": object_id,
                "action": action,
                "timestamp": timestamp,
                "ip": ip,
            }
        )
        if caller is not UNSET:
            field_dict["caller"] = caller
        if actor_type is not UNSET:
            field_dict["actor_type"] = actor_type
        if actor_id is not UNSET:
            field_dict["actor_id"] = actor_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        object_id = d.pop("object_id")

        action = AuditLogEntryAction(d.pop("action"))

        timestamp = datetime.datetime.fromisoformat(d.pop("timestamp"))

        ip = d.pop("ip")

        caller = d.pop("caller", UNSET)

        _actor_type = d.pop("actor_type", UNSET)
        actor_type: AuditLogEntryActorType | Unset
        if isinstance(_actor_type, Unset):
            actor_type = UNSET
        else:
            actor_type = AuditLogEntryActorType(_actor_type)

        actor_id = d.pop("actor_id", UNSET)

        audit_log_entry = cls(
            object_id=object_id,
            action=action,
            timestamp=timestamp,
            ip=ip,
            caller=caller,
            actor_type=actor_type,
            actor_id=actor_id,
        )

        audit_log_entry.additional_properties = d
        return audit_log_entry

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
