# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from enum import StrEnum


class AuditLogEntryAction(StrEnum):
    CREATE = "create"
    DELETE = "delete"
    READ = "read"
    UPDATE = "update"

    def __str__(self) -> str:
        return str(self.value)
