# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from enum import StrEnum


class AuditLogEntryActorType(StrEnum):
    SESSION = "session"
    TOKEN = "token"

    def __str__(self) -> str:
        return str(self.value)
