# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.audit_log_entry_action import AuditLogEntryAction
from ..models.audit_log_entry_actor_type import AuditLogEntryActorType
from ..types import UNSET, Unset

T = TypeVar("T", bound="AuditLogEntry")


@_attrs_define
class AuditLogEntry:
    """
    Attributes:
        id (int): This entry's own id - stable and strictly increasing, so it
            doubles as the cursor for the `after` query parameter.
        object_id (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        action (AuditLogEntryAction):
        timestamp (datetime.datetime):
        ip (str): The request's source IP. Unlike caller, this is never
            self-reported - it's the one piece of the request nobody gets
            to lie about via a header. Currently the immediate TCP peer's
            address; this service isn't deployed behind a reverse proxy or
            load balancer, so X-Forwarded-For (or similar) support isn't
            implemented yet.
        variant_id (UUID | Unset): The UUID of the object the entry is about. `object_id` is only its name, which
            several variants can share. Left out of an entry written before this was recorded.
        caller (str | Unset): The caller's presented identity, if any.
        actor_type (AuditLogEntryActorType | Unset): The kind of verified credential that authenticated this call -
            absent for an unauthenticated read. Unlike caller, this is
            never self-reported.
        actor_id (str | Unset): The specific token id or admin account this call was
            authenticated as - absent for an unauthenticated read.
    """

    id: int
    object_id: str
    action: AuditLogEntryAction
    timestamp: datetime.datetime
    ip: str
    variant_id: UUID | Unset = UNSET
    caller: str | Unset = UNSET
    actor_type: AuditLogEntryActorType | Unset = UNSET
    actor_id: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        object_id = self.object_id

        action = self.action.value

        timestamp = self.timestamp.isoformat()

        ip = self.ip

        variant_id: str | Unset = UNSET
        if not isinstance(self.variant_id, Unset):
            variant_id = str(self.variant_id)

        caller = self.caller

        actor_type: str | Unset = UNSET
        if not isinstance(self.actor_type, Unset):
            actor_type = self.actor_type.value

        actor_id = self.actor_id

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "id": id,
                "object_id": object_id,
                "action": action,
                "timestamp": timestamp,
                "ip": ip,
            }
        )
        if variant_id is not UNSET:
            field_dict["variant_id"] = variant_id
        if caller is not UNSET:
            field_dict["caller"] = caller
        if actor_type is not UNSET:
            field_dict["actor_type"] = actor_type
        if actor_id is not UNSET:
            field_dict["actor_id"] = actor_id

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        object_id = d.pop("object_id")

        action = AuditLogEntryAction(d.pop("action"))

        timestamp = datetime.datetime.fromisoformat(d.pop("timestamp"))

        ip = d.pop("ip")

        _variant_id = d.pop("variant_id", UNSET)
        variant_id: UUID | Unset
        variant_id = UNSET if isinstance(_variant_id, Unset) else UUID(_variant_id)

        caller = d.pop("caller", UNSET)

        _actor_type = d.pop("actor_type", UNSET)
        actor_type: AuditLogEntryActorType | Unset
        if isinstance(_actor_type, Unset):
            actor_type = UNSET
        else:
            actor_type = AuditLogEntryActorType(_actor_type)

        actor_id = d.pop("actor_id", UNSET)

        audit_log_entry = cls(
            id=id,
            object_id=object_id,
            action=action,
            timestamp=timestamp,
            ip=ip,
            variant_id=variant_id,
            caller=caller,
            actor_type=actor_type,
            actor_id=actor_id,
        )

        audit_log_entry.additional_properties = d
        return audit_log_entry

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
