# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

T = TypeVar("T", bound="AuthStatus")


@_attrs_define
class AuthStatus:
    """
    Attributes:
        bootstrapped (bool): Whether an admin account has been created yet.
        authenticated (bool): Whether the request carries a valid, unexpired session cookie.
            False for no cookie, an expired one or one that doesn't match a
            session - still a 200, so a client can ask without being
            answered with a 401.
    """

    bootstrapped: bool
    authenticated: bool
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        bootstrapped = self.bootstrapped

        authenticated = self.authenticated

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "bootstrapped": bootstrapped,
                "authenticated": authenticated,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        bootstrapped = d.pop("bootstrapped")

        authenticated = d.pop("authenticated")

        auth_status = cls(
            bootstrapped=bootstrapped,
            authenticated=authenticated,
        )

        auth_status.additional_properties = d
        return auth_status

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
