# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..models.token_allowed_actions_item import TokenAllowedActionsItem
from ..models.token_status import TokenStatus
from ..types import UNSET, Unset

T = TypeVar("T", bound="ConsumerTokenWithValue")


@_attrs_define
class ConsumerTokenWithValue:
    """
    Attributes:
        id (str):
        consumer (str):
        description (str):
        created_at (datetime.datetime):
        expires_at (datetime.datetime):
        revoked (bool):
        value (str): The raw consumer token. Shown here once, at creation, and
            never again.
        last_used_at (datetime.datetime | Unset): Absent if this token has never authenticated a request.
        status (TokenStatus | Unset): What the token is right now, by the server's own clock: `revoked`
            if it was revoked (even if it has also expired), `expired` if its
            `expires_at` has passed, `active` otherwise. Always sent by this
            server; optional in the schema so a client generated from it still
            reads a response from an older one.
        allowed_actions (list[TokenAllowedActionsItem] | Unset): What may be done to the token in its current state:
            `rotate` and
            `revoke` while it is `active`, only `purge` once it is `expired` or
            `revoked`. The endpoints enforce the same rule themselves - a purge
            of an active token is still a 409 - so a client that acts on a stale
            view gets the server's answer. Hiding a button is cosmetic; this is
            what to show.
    """

    id: str
    consumer: str
    description: str
    created_at: datetime.datetime
    expires_at: datetime.datetime
    revoked: bool
    value: str
    last_used_at: datetime.datetime | Unset = UNSET
    status: TokenStatus | Unset = UNSET
    allowed_actions: list[TokenAllowedActionsItem] | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        consumer = self.consumer

        description = self.description

        created_at = self.created_at.isoformat()

        expires_at = self.expires_at.isoformat()

        revoked = self.revoked

        value = self.value

        last_used_at: str | Unset = UNSET
        if not isinstance(self.last_used_at, Unset):
            last_used_at = self.last_used_at.isoformat()

        status: str | Unset = UNSET
        if not isinstance(self.status, Unset):
            status = self.status.value

        allowed_actions: list[str] | Unset = UNSET
        if not isinstance(self.allowed_actions, Unset):
            allowed_actions = []
            for componentsschemas_token_allowed_actions_item_data in self.allowed_actions:
                componentsschemas_token_allowed_actions_item = (
                    componentsschemas_token_allowed_actions_item_data.value
                )
                allowed_actions.append(componentsschemas_token_allowed_actions_item)

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "id": id,
                "consumer": consumer,
                "description": description,
                "created_at": created_at,
                "expires_at": expires_at,
                "revoked": revoked,
                "value": value,
            }
        )
        if last_used_at is not UNSET:
            field_dict["last_used_at"] = last_used_at
        if status is not UNSET:
            field_dict["status"] = status
        if allowed_actions is not UNSET:
            field_dict["allowed_actions"] = allowed_actions

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        consumer = d.pop("consumer")

        description = d.pop("description")

        created_at = datetime.datetime.fromisoformat(d.pop("created_at"))

        expires_at = datetime.datetime.fromisoformat(d.pop("expires_at"))

        revoked = d.pop("revoked")

        value = d.pop("value")

        _last_used_at = d.pop("last_used_at", UNSET)
        last_used_at: datetime.datetime | Unset
        if isinstance(_last_used_at, Unset):
            last_used_at = UNSET
        else:
            last_used_at = datetime.datetime.fromisoformat(_last_used_at)

        _status = d.pop("status", UNSET)
        status: TokenStatus | Unset
        status = UNSET if isinstance(_status, Unset) else TokenStatus(_status)

        _allowed_actions = d.pop("allowed_actions", UNSET)
        allowed_actions: list[TokenAllowedActionsItem] | Unset = UNSET
        if _allowed_actions is not UNSET:
            allowed_actions = []
            for componentsschemas_token_allowed_actions_item_data in _allowed_actions:
                componentsschemas_token_allowed_actions_item = TokenAllowedActionsItem(
                    componentsschemas_token_allowed_actions_item_data
                )

                allowed_actions.append(componentsschemas_token_allowed_actions_item)

        consumer_token_with_value = cls(
            id=id,
            consumer=consumer,
            description=description,
            created_at=created_at,
            expires_at=expires_at,
            revoked=revoked,
            value=value,
            last_used_at=last_used_at,
            status=status,
            allowed_actions=allowed_actions,
        )

        consumer_token_with_value.additional_properties = d
        return consumer_token_with_value

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
