# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

T = TypeVar("T", bound="CreateTokenRequest")


@_attrs_define
class CreateTokenRequest:
    """
    Attributes:
        description (str):
        ttl_seconds (int): How long a token stays valid for, starting now. The default is 90
            days (7776000), and the cap is 365 days (31536000): a longer
            lifetime is a 422 that names the limit. A zero or negative value is
            a 400. The cap applies when a token is minted or rotated; a token
            issued before it existed keeps working until it expires.

            The field stays `required` so generated clients keep a plain
            integer rather than an optional one, which would change their types
            for a limit they don't need. A request that leaves it out anyway is
            given the default rather than rejected.
    """

    description: str
    ttl_seconds: int
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        description = self.description

        ttl_seconds = self.ttl_seconds

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "description": description,
                "ttl_seconds": ttl_seconds,
            }
        )

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        description = d.pop("description")

        ttl_seconds = d.pop("ttl_seconds")

        create_token_request = cls(
            description=description,
            ttl_seconds=ttl_seconds,
        )

        create_token_request.additional_properties = d
        return create_token_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
