# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="ObjectMetadata")


@_attrs_define
class ObjectMetadata:
    """
    Attributes:
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        tags (list[str]): Labels for grouping and filtering objects (`GET /objects?tag=`).
            Free-form, 1 to 32 characters from `a-z 0-9 . _ / -`, at most 10
            per object. Uppercase is converted to lowercase and duplicates are dropped.
            Metadata only - never part of the sealed value. A response always
            carries the array, empty when the object has none.
        used_by (list[str] | Unset): The consumers (repos or hosts) recorded as depending on this
            object. Set at creation, and replaceable later via
            UpdateObjectRequest's own used_by field - a plain value update
            that omits it leaves the list as it was.
        description (str | Unset): A free-text label set at creation, for a reader who only knows the
            slug. Fixed at creation - there is no way to change it later.
        keep_readable_copy (bool | Unset): Requests that the owner's own escrowed identity public key be
            included as an additional decrypt recipient, alongside whatever
            consumer recipients the client already resolved
            (specs/secret-objects/spec.md's "Opt-in owner-recipient inclusion
            at create time" requirement). Omitting this field (the default)
            means the owner is not added as a recipient - this service never
            makes ownership imply decrypt access on its own.

            This is a client-side sealing instruction, not something this
            service enforces or verifies: it never decrypts, and never adds a
            recipient to `value` itself - the caller has to add the owner's
            public key (`GET /auth/identity`) to its own recipient list before
            sealing. A create or update response echoes back exactly what that
            same request asked for; it isn't persisted, so a later fetch never
            carries this field.
    """

    slug: str
    tags: list[str]
    used_by: list[str] | Unset = UNSET
    description: str | Unset = UNSET
    keep_readable_copy: bool | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        slug = self.slug

        tags = self.tags

        used_by: list[str] | Unset = UNSET
        if not isinstance(self.used_by, Unset):
            used_by = self.used_by

        description = self.description

        keep_readable_copy = self.keep_readable_copy

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "slug": slug,
                "tags": tags,
            }
        )
        if used_by is not UNSET:
            field_dict["used_by"] = used_by
        if description is not UNSET:
            field_dict["description"] = description
        if keep_readable_copy is not UNSET:
            field_dict["keep_readable_copy"] = keep_readable_copy

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        slug = d.pop("slug")

        tags = cast(list[str], d.pop("tags"))

        used_by = cast(list[str], d.pop("used_by", UNSET))

        description = d.pop("description", UNSET)

        keep_readable_copy = d.pop("keep_readable_copy", UNSET)

        object_metadata = cls(
            slug=slug,
            tags=tags,
            used_by=used_by,
            description=description,
            keep_readable_copy=keep_readable_copy,
        )

        object_metadata.additional_properties = d
        return object_metadata

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
