# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="ObjectMetadata")


@_attrs_define
class ObjectMetadata:
    """
    Attributes:
        id (str):
        used_by (list[str] | Unset): The consumers (repos or hosts) recorded as depending on this
            object. Set at creation; unaffected by later value updates.
        description (str | Unset): A free-text label set at creation, for a reader who only knows the
            id. Fixed at creation - the same as used_by, it is unaffected by a
            later value update.
    """

    id: str
    used_by: list[str] | Unset = UNSET
    description: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        used_by: list[str] | Unset = UNSET
        if not isinstance(self.used_by, Unset):
            used_by = self.used_by

        description = self.description

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "id": id,
            }
        )
        if used_by is not UNSET:
            field_dict["used_by"] = used_by
        if description is not UNSET:
            field_dict["description"] = description

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        used_by = cast(list[str], d.pop("used_by", UNSET))

        description = d.pop("description", UNSET)

        object_metadata = cls(
            id=id,
            used_by=used_by,
            description=description,
        )

        object_metadata.additional_properties = d
        return object_metadata

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
