# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import TYPE_CHECKING, Any, TypeVar, cast
from uuid import UUID

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

if TYPE_CHECKING:
    from ..models.actor import Actor


T = TypeVar("T", bound="ObjectMetadata")


@_attrs_define
class ObjectMetadata:
    """
    Attributes:
        id (UUID): The object's UUID. Several objects can share a name (each is a variant, with its own value and
            consumers), so this is what tells them apart and what `id` selects.
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        tags (list[str]): Labels for grouping and filtering objects (`GET /objects?tag=`).
            Free-form, 1 to 32 characters from `a-z 0-9 . _ / -`, at most 10
            per object. Uppercase is converted to lowercase and duplicates are dropped.
            Metadata only - never part of the sealed value. A response always
            carries the array, empty when the object has none.
        used_by (list[str] | Unset): The consumers (repos or hosts) recorded as depending on this
            object. Set at creation, and replaceable later via
            UpdateObjectRequest's own used_by field - a plain value update
            that omits it leaves the list as it was.
            A consumer named more than once is recorded once.
        description (str | Unset): A free-text label set at creation, for a reader who only knows the
            slug. Fixed at creation - there is no way to change it later.
        keep_readable_copy (bool | Unset): Requests that the owner's own escrowed identity public key be
            included as an additional decrypt recipient, alongside whatever
            consumer recipients the client already resolved
            (specs/secret-objects/spec.md's "Opt-in owner-recipient inclusion
            at create time" requirement). Omitting this field (the default)
            means the owner is not added as a recipient - this service never
            makes ownership imply decrypt access on its own.

            This is a client-side sealing instruction, not something this
            service enforces or verifies: it never decrypts, and never adds a
            recipient to `value` itself - the caller has to add the owner's
            public key (`GET /auth/identity`) to its own recipient list before
            sealing. A create or update response echoes back exactly what that
            same request asked for; it isn't persisted, so a later fetch never
            carries this field.
        created_at (datetime.datetime | Unset): When the object was created. Returned by `GET /objects`; left
            out of a create or update response.
        updated_at (datetime.datetime | Unset): When the object's value was last replaced - equal to
            `created_at` for an object never updated. Returned by
            `GET /objects`; left out of a create or update response.
        created_by (Actor | Unset): Who performed an audited write. `type` is `session` (the admin
            account, `id` is its actor id), `token` (a write token, `id` is its
            token id) or `consumer_token` (a consumer token, `id` is its id) -
            the same values `GET /audit-log` reports.
        updated_by (Actor | Unset): Who performed an audited write. `type` is `session` (the admin
            account, `id` is its actor id), `token` (a write token, `id` is its
            token id) or `consumer_token` (a consumer token, `id` is its id) -
            the same values `GET /audit-log` reports.
    """

    id: UUID
    slug: str
    tags: list[str]
    used_by: list[str] | Unset = UNSET
    description: str | Unset = UNSET
    keep_readable_copy: bool | Unset = UNSET
    created_at: datetime.datetime | Unset = UNSET
    updated_at: datetime.datetime | Unset = UNSET
    created_by: Actor | Unset = UNSET
    updated_by: Actor | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = str(self.id)

        slug = self.slug

        tags = self.tags

        used_by: list[str] | Unset = UNSET
        if not isinstance(self.used_by, Unset):
            used_by = self.used_by

        description = self.description

        keep_readable_copy = self.keep_readable_copy

        created_at: str | Unset = UNSET
        if not isinstance(self.created_at, Unset):
            created_at = self.created_at.isoformat()

        updated_at: str | Unset = UNSET
        if not isinstance(self.updated_at, Unset):
            updated_at = self.updated_at.isoformat()

        created_by: dict[str, Any] | Unset = UNSET
        if not isinstance(self.created_by, Unset):
            created_by = self.created_by.to_dict()

        updated_by: dict[str, Any] | Unset = UNSET
        if not isinstance(self.updated_by, Unset):
            updated_by = self.updated_by.to_dict()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "id": id,
                "slug": slug,
                "tags": tags,
            }
        )
        if used_by is not UNSET:
            field_dict["used_by"] = used_by
        if description is not UNSET:
            field_dict["description"] = description
        if keep_readable_copy is not UNSET:
            field_dict["keep_readable_copy"] = keep_readable_copy
        if created_at is not UNSET:
            field_dict["created_at"] = created_at
        if updated_at is not UNSET:
            field_dict["updated_at"] = updated_at
        if created_by is not UNSET:
            field_dict["created_by"] = created_by
        if updated_by is not UNSET:
            field_dict["updated_by"] = updated_by

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        from ..models.actor import Actor  # noqa: PLC0415

        d = dict(src_dict)
        id = UUID(d.pop("id"))

        slug = d.pop("slug")

        tags = cast(list[str], d.pop("tags"))

        used_by = cast(list[str], d.pop("used_by", UNSET))

        description = d.pop("description", UNSET)

        keep_readable_copy = d.pop("keep_readable_copy", UNSET)

        _created_at = d.pop("created_at", UNSET)
        created_at: datetime.datetime | Unset
        if isinstance(_created_at, Unset):
            created_at = UNSET
        else:
            created_at = datetime.datetime.fromisoformat(_created_at)

        _updated_at = d.pop("updated_at", UNSET)
        updated_at: datetime.datetime | Unset
        if isinstance(_updated_at, Unset):
            updated_at = UNSET
        else:
            updated_at = datetime.datetime.fromisoformat(_updated_at)

        _created_by = d.pop("created_by", UNSET)
        created_by: Actor | Unset
        created_by = UNSET if isinstance(_created_by, Unset) else Actor.from_dict(_created_by)

        _updated_by = d.pop("updated_by", UNSET)
        updated_by: Actor | Unset
        updated_by = UNSET if isinstance(_updated_by, Unset) else Actor.from_dict(_updated_by)

        object_metadata = cls(
            id=id,
            slug=slug,
            tags=tags,
            used_by=used_by,
            description=description,
            keep_readable_copy=keep_readable_copy,
            created_at=created_at,
            updated_at=updated_at,
            created_by=created_by,
            updated_by=updated_by,
        )

        object_metadata.additional_properties = d
        return object_metadata

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
