# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from enum import StrEnum


class QueryAuditLogOrder(StrEnum):
    ASC = "asc"
    DESC = "desc"

    def __str__(self) -> str:
        return str(self.value)
