# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from enum import StrEnum


class TokenStatus(StrEnum):
    ACTIVE = "active"
    EXPIRED = "expired"
    REVOKED = "revoked"

    def __str__(self) -> str:
        return str(self.value)
