# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from enum import StrEnum


class TokenAllowedActionsItem(StrEnum):
    PURGE = "purge"
    REVOKE = "revoke"
    ROTATE = "rotate"

    def __str__(self) -> str:
        return str(self.value)
