# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="TokenWithValue")


@_attrs_define
class TokenWithValue:
    """
    Attributes:
        id (str):
        description (str):
        created_at (datetime.datetime):
        expires_at (datetime.datetime):
        revoked (bool):
        value (str): The raw bearer token. Shown here once, at creation, and
            never again - the same as a token issued via the `token`
            CLI command.
        owner (str | Unset): The admin account that created this token over HTTP. Absent
            for a token issued via the `token` CLI command, which has no
            session to attribute to - never a guessed value.
        last_used_at (datetime.datetime | Unset): Absent if this token has never authenticated a request.
    """

    id: str
    description: str
    created_at: datetime.datetime
    expires_at: datetime.datetime
    revoked: bool
    value: str
    owner: str | Unset = UNSET
    last_used_at: datetime.datetime | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        description = self.description

        created_at = self.created_at.isoformat()

        expires_at = self.expires_at.isoformat()

        revoked = self.revoked

        value = self.value

        owner = self.owner

        last_used_at: str | Unset = UNSET
        if not isinstance(self.last_used_at, Unset):
            last_used_at = self.last_used_at.isoformat()

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "id": id,
                "description": description,
                "created_at": created_at,
                "expires_at": expires_at,
                "revoked": revoked,
                "value": value,
            }
        )
        if owner is not UNSET:
            field_dict["owner"] = owner
        if last_used_at is not UNSET:
            field_dict["last_used_at"] = last_used_at

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        description = d.pop("description")

        created_at = datetime.datetime.fromisoformat(d.pop("created_at"))

        expires_at = datetime.datetime.fromisoformat(d.pop("expires_at"))

        revoked = d.pop("revoked")

        value = d.pop("value")

        owner = d.pop("owner", UNSET)

        _last_used_at = d.pop("last_used_at", UNSET)
        last_used_at: datetime.datetime | Unset
        if isinstance(_last_used_at, Unset):
            last_used_at = UNSET
        else:
            last_used_at = datetime.datetime.fromisoformat(_last_used_at)

        token_with_value = cls(
            id=id,
            description=description,
            created_at=created_at,
            expires_at=expires_at,
            revoked=revoked,
            value=value,
            owner=owner,
            last_used_at=last_used_at,
        )

        token_with_value.additional_properties = d
        return token_with_value

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
