# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from __future__ import annotations

import datetime
from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="TokenMetadata")


@_attrs_define
class TokenMetadata:
    """
    Attributes:
        id (str):
        description (str):
        created_at (datetime.datetime):
        expires_at (datetime.datetime):
        revoked (bool):
        owner (str | Unset): The admin account that created this token over HTTP. Absent
            for a token issued via the `token` CLI command, which has no
            session to attribute to - never a guessed value.
    """

    id: str
    description: str
    created_at: datetime.datetime
    expires_at: datetime.datetime
    revoked: bool
    owner: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        id = self.id

        description = self.description

        created_at = self.created_at.isoformat()

        expires_at = self.expires_at.isoformat()

        revoked = self.revoked

        owner = self.owner

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "id": id,
                "description": description,
                "created_at": created_at,
                "expires_at": expires_at,
                "revoked": revoked,
            }
        )
        if owner is not UNSET:
            field_dict["owner"] = owner

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        id = d.pop("id")

        description = d.pop("description")

        created_at = datetime.datetime.fromisoformat(d.pop("created_at"))

        expires_at = datetime.datetime.fromisoformat(d.pop("expires_at"))

        revoked = d.pop("revoked")

        owner = d.pop("owner", UNSET)

        token_metadata = cls(
            id=id,
            description=description,
            created_at=created_at,
            expires_at=expires_at,
            revoked=revoked,
            owner=owner,
        )

        token_metadata.additional_properties = d
        return token_metadata

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
