# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="UpdateConsumerRequest")


@_attrs_define
class UpdateConsumerRequest:
    """At least one of `name` or `public_key` is required (enforced by
    `minProperties` above); a field left out leaves that aspect of the
    consumer unchanged. There is no way to clear a registered public
    key through this request, only to set or replace one.

        Attributes:
            name (str | Unset): The consumer's new name. If it already matches another
                recorded consumer, the two merge - every object recording
                either ends up recording just the new name, no duplicates. A
                registered public key survives the merge: the target name's
                own key wins if it already had one, otherwise the renamed
                consumer's key carries over.
            public_key (str | Unset): Registers or replaces the consumer's age public key, safe to
                store server-side since it's public. A consumer's private key
                SHALL NOT be sent here or anywhere else in this API - this
                field only ever accepts a public key. Registering a key
                doesn't require the consumer to already be recorded anywhere;
                a name never referenced by any object's `used_by` list yet is
                accepted the same as an existing one.
    """

    name: str | Unset = UNSET
    public_key: str | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        name = self.name

        public_key = self.public_key

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update({})
        if name is not UNSET:
            field_dict["name"] = name
        if public_key is not UNSET:
            field_dict["public_key"] = public_key

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        name = d.pop("name", UNSET)

        public_key = d.pop("public_key", UNSET)

        update_consumer_request = cls(
            name=name,
            public_key=public_key,
        )

        update_consumer_request.additional_properties = d
        return update_consumer_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
