# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from __future__ import annotations

from collections.abc import Mapping
from typing import Any, TypeVar, cast

from attrs import define as _attrs_define
from attrs import field as _attrs_field

from ..types import UNSET, Unset

T = TypeVar("T", bound="UpdateObjectRequest")


@_attrs_define
class UpdateObjectRequest:
    """
    Attributes:
        value (str): The new sealed (encrypted) value, base64-encoded. It has to be
            a well-formed age file naming at least one recipient; the
            service reads only its header, never the payload. At most 1 MiB
            once decoded.
        used_by (list[str] | Unset): The consumers (repos or hosts) recorded as depending on this
            object. Set at creation, and replaceable later via
            UpdateObjectRequest's own used_by field - a plain value update
            that omits it leaves the list as it was.
            A consumer named more than once is recorded once.
        tags (list[str] | Unset): Labels for grouping and filtering objects (`GET /objects?tag=`).
            Free-form, 1 to 32 characters from `a-z 0-9 . _ / -`, at most 10
            per object. Uppercase is converted to lowercase and duplicates are dropped.
            Metadata only - never part of the sealed value. A response always
            carries the array, empty when the object has none.
        keep_readable_copy (bool | Unset): Requests that the owner's own escrowed identity public key be
            included as an additional decrypt recipient, alongside whatever
            consumer recipients the client already resolved
            (specs/secret-objects/spec.md's "Opt-in owner-recipient inclusion
            at create time" requirement). Omitting this field (the default)
            means the owner is not added as a recipient - this service never
            makes ownership imply decrypt access on its own.

            This is a client-side sealing instruction, not something this
            service enforces or verifies: it never decrypts, and never adds a
            recipient to `value` itself - the caller has to add the owner's
            public key (`GET /auth/identity`) to its own recipient list before
            sealing. A create or update response echoes back exactly what that
            same request asked for; it isn't persisted, so a later fetch never
            carries this field.
    """

    value: str
    used_by: list[str] | Unset = UNSET
    tags: list[str] | Unset = UNSET
    keep_readable_copy: bool | Unset = UNSET
    additional_properties: dict[str, Any] = _attrs_field(init=False, factory=dict)

    def to_dict(self) -> dict[str, Any]:
        value = self.value

        used_by: list[str] | Unset = UNSET
        if not isinstance(self.used_by, Unset):
            used_by = self.used_by

        tags: list[str] | Unset = UNSET
        if not isinstance(self.tags, Unset):
            tags = self.tags

        keep_readable_copy = self.keep_readable_copy

        field_dict: dict[str, Any] = {}
        field_dict.update(self.additional_properties)
        field_dict.update(
            {
                "value": value,
            }
        )
        if used_by is not UNSET:
            field_dict["used_by"] = used_by
        if tags is not UNSET:
            field_dict["tags"] = tags
        if keep_readable_copy is not UNSET:
            field_dict["keep_readable_copy"] = keep_readable_copy

        return field_dict

    @classmethod
    def from_dict(cls: type[T], src_dict: Mapping[str, Any]) -> T:
        d = dict(src_dict)
        value = d.pop("value")

        used_by = cast(list[str], d.pop("used_by", UNSET))

        tags = cast(list[str], d.pop("tags", UNSET))

        keep_readable_copy = d.pop("keep_readable_copy", UNSET)

        update_object_request = cls(
            value=value,
            used_by=used_by,
            tags=tags,
            keep_readable_copy=keep_readable_copy,
        )

        update_object_request.additional_properties = d
        return update_object_request

    @property
    def additional_keys(self) -> list[str]:
        return list(self.additional_properties.keys())

    def __getitem__(self, key: str) -> Any:
        return self.additional_properties[key]

    def __setitem__(self, key: str, value: Any) -> None:
        self.additional_properties[key] = value

    def __delitem__(self, key: str) -> None:
        del self.additional_properties[key]

    def __contains__(self, key: str) -> bool:
        return key in self.additional_properties
