# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.ready import Ready
from ...types import Response


def _get_kwargs() -> dict[str, Any]:

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/readyz",
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Ready | None:
    if response.status_code == 200:
        response_200 = Ready.from_dict(response.json())

        return response_200

    if response.status_code == 503:
        response_503 = Ready.from_dict(response.json())

        return response_503

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Ready]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
) -> Response[Ready]:
    """Readiness

     Answers 200 when the database can serve a request and 503 when it
    can't. The container image's own health check asks this, so a
    container whose database has become unusable shows as unhealthy,
    where `/healthz` would stay green because the process is still up.
    Unauthenticated like `/healthz`, so a failure never says why - the
    reason goes to the server's log.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Ready]
    """

    kwargs = _get_kwargs()

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
) -> Ready | None:
    """Readiness

     Answers 200 when the database can serve a request and 503 when it
    can't. The container image's own health check asks this, so a
    container whose database has become unusable shows as unhealthy,
    where `/healthz` would stay green because the process is still up.
    Unauthenticated like `/healthz`, so a failure never says why - the
    reason goes to the server's log.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Ready
    """

    return sync_detailed(
        client=client,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
) -> Response[Ready]:
    """Readiness

     Answers 200 when the database can serve a request and 503 when it
    can't. The container image's own health check asks this, so a
    container whose database has become unusable shows as unhealthy,
    where `/healthz` would stay green because the process is still up.
    Unauthenticated like `/healthz`, so a failure never says why - the
    reason goes to the server's log.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Ready]
    """

    kwargs = _get_kwargs()

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
) -> Ready | None:
    """Readiness

     Answers 200 when the database can serve a request and 503 when it
    can't. The container image's own health check asks this, so a
    container whose database has become unusable shows as unhealthy,
    where `/healthz` would stay green because the process is still up.
    Unauthenticated like `/healthz`, so a failure never says why - the
    reason goes to the server's log.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Ready
    """

    return (
        await asyncio_detailed(
            client=client,
        )
    ).parsed
