# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.mcp_body import McpBody
from ...models.mcp_response_200 import McpResponse200
from ...types import Response


def _get_kwargs(
    *,
    body: McpBody,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/mcp",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | McpResponse200 | None:
    if response.status_code == 200:
        response_200 = McpResponse200.from_dict(response.json())

        return response_200

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | McpResponse200]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: McpBody,
) -> Response[Error | McpResponse200]:
    """MCP (Model Context Protocol) endpoint

     Serves the MCP Streamable HTTP transport - JSON-RPC 2.0 messages
    exchanging tool calls with an MCP-capable client
    (https://modelcontextprotocol.io). Exposes five tools mirroring
    hush-hush-cli's own operations one-to-one: inject, get, update,
    delete, list (docs/adr/0019-mcp-endpoint.md).

    Gated the same way every other write route is, applied uniformly
    across all five tools - including get and list, which are
    unauthenticated (get) or write-token-or-session-gated (list) over
    their plain HTTP equivalents. One authenticated MCP session
    performs all five operations, rather than each tool reproducing
    its HTTP twin's own auth shape.

    The request and response bodies are MCP's own JSON-RPC 2.0
    envelope, not described further here - OpenAPI can't usefully
    express per-tool dynamic dispatch. The real per-tool contract is
    the JSON Schema each tool's Go input/output type generates at
    compile time, discoverable from a running server's own
    `tools/list` call, not from this document.

    Args:
        body (McpBody): An MCP JSON-RPC 2.0 request.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | McpResponse200]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: McpBody,
) -> Error | McpResponse200 | None:
    """MCP (Model Context Protocol) endpoint

     Serves the MCP Streamable HTTP transport - JSON-RPC 2.0 messages
    exchanging tool calls with an MCP-capable client
    (https://modelcontextprotocol.io). Exposes five tools mirroring
    hush-hush-cli's own operations one-to-one: inject, get, update,
    delete, list (docs/adr/0019-mcp-endpoint.md).

    Gated the same way every other write route is, applied uniformly
    across all five tools - including get and list, which are
    unauthenticated (get) or write-token-or-session-gated (list) over
    their plain HTTP equivalents. One authenticated MCP session
    performs all five operations, rather than each tool reproducing
    its HTTP twin's own auth shape.

    The request and response bodies are MCP's own JSON-RPC 2.0
    envelope, not described further here - OpenAPI can't usefully
    express per-tool dynamic dispatch. The real per-tool contract is
    the JSON Schema each tool's Go input/output type generates at
    compile time, discoverable from a running server's own
    `tools/list` call, not from this document.

    Args:
        body (McpBody): An MCP JSON-RPC 2.0 request.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | McpResponse200
    """

    return sync_detailed(
        client=client,
        body=body,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: McpBody,
) -> Response[Error | McpResponse200]:
    """MCP (Model Context Protocol) endpoint

     Serves the MCP Streamable HTTP transport - JSON-RPC 2.0 messages
    exchanging tool calls with an MCP-capable client
    (https://modelcontextprotocol.io). Exposes five tools mirroring
    hush-hush-cli's own operations one-to-one: inject, get, update,
    delete, list (docs/adr/0019-mcp-endpoint.md).

    Gated the same way every other write route is, applied uniformly
    across all five tools - including get and list, which are
    unauthenticated (get) or write-token-or-session-gated (list) over
    their plain HTTP equivalents. One authenticated MCP session
    performs all five operations, rather than each tool reproducing
    its HTTP twin's own auth shape.

    The request and response bodies are MCP's own JSON-RPC 2.0
    envelope, not described further here - OpenAPI can't usefully
    express per-tool dynamic dispatch. The real per-tool contract is
    the JSON Schema each tool's Go input/output type generates at
    compile time, discoverable from a running server's own
    `tools/list` call, not from this document.

    Args:
        body (McpBody): An MCP JSON-RPC 2.0 request.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | McpResponse200]
    """

    kwargs = _get_kwargs(
        body=body,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: McpBody,
) -> Error | McpResponse200 | None:
    """MCP (Model Context Protocol) endpoint

     Serves the MCP Streamable HTTP transport - JSON-RPC 2.0 messages
    exchanging tool calls with an MCP-capable client
    (https://modelcontextprotocol.io). Exposes five tools mirroring
    hush-hush-cli's own operations one-to-one: inject, get, update,
    delete, list (docs/adr/0019-mcp-endpoint.md).

    Gated the same way every other write route is, applied uniformly
    across all five tools - including get and list, which are
    unauthenticated (get) or write-token-or-session-gated (list) over
    their plain HTTP equivalents. One authenticated MCP session
    performs all five operations, rather than each tool reproducing
    its HTTP twin's own auth shape.

    The request and response bodies are MCP's own JSON-RPC 2.0
    envelope, not described further here - OpenAPI can't usefully
    express per-tool dynamic dispatch. The real per-tool contract is
    the JSON Schema each tool's Go input/output type generates at
    compile time, discoverable from a running server's own
    `tools/list` call, not from this document.

    Args:
        body (McpBody): An MCP JSON-RPC 2.0 request.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | McpResponse200
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
        )
    ).parsed
