# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.add_consumer_request import AddConsumerRequest
from ...models.consumer_entry import ConsumerEntry
from ...models.error import Error
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    body: AddConsumerRequest,
    x_csrf_token: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_csrf_token, Unset):
        headers["X-CSRF-Token"] = x_csrf_token

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/consumers",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> ConsumerEntry | Error | None:
    if response.status_code == 201:
        response_201 = ConsumerEntry.from_dict(response.json())

        return response_201

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 409:
        response_409 = Error.from_dict(response.json())

        return response_409

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[ConsumerEntry | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: AddConsumerRequest,
    x_csrf_token: str | Unset = UNSET,
) -> Response[ConsumerEntry | Error]:
    """Add a consumer with no secret referencing it yet

     Adds `name` to the directory (`alrayyes/hush-hush#324`) without
    requiring any object's `used_by` list to reference it first -
    unlike every other consumer here, which only ever exist because
    some object's `used_by` recorded them. The new entry appears in
    `GET /consumers` with a `secret_count` of 0 until something
    actually uses it. A session-authenticated call needs its CSRF
    token too; a bearer-token-authenticated one doesn't.

    Args:
        x_csrf_token (str | Unset):
        body (AddConsumerRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ConsumerEntry | Error]
    """

    kwargs = _get_kwargs(
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: AddConsumerRequest,
    x_csrf_token: str | Unset = UNSET,
) -> ConsumerEntry | Error | None:
    """Add a consumer with no secret referencing it yet

     Adds `name` to the directory (`alrayyes/hush-hush#324`) without
    requiring any object's `used_by` list to reference it first -
    unlike every other consumer here, which only ever exist because
    some object's `used_by` recorded them. The new entry appears in
    `GET /consumers` with a `secret_count` of 0 until something
    actually uses it. A session-authenticated call needs its CSRF
    token too; a bearer-token-authenticated one doesn't.

    Args:
        x_csrf_token (str | Unset):
        body (AddConsumerRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ConsumerEntry | Error
    """

    return sync_detailed(
        client=client,
        body=body,
        x_csrf_token=x_csrf_token,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: AddConsumerRequest,
    x_csrf_token: str | Unset = UNSET,
) -> Response[ConsumerEntry | Error]:
    """Add a consumer with no secret referencing it yet

     Adds `name` to the directory (`alrayyes/hush-hush#324`) without
    requiring any object's `used_by` list to reference it first -
    unlike every other consumer here, which only ever exist because
    some object's `used_by` recorded them. The new entry appears in
    `GET /consumers` with a `secret_count` of 0 until something
    actually uses it. A session-authenticated call needs its CSRF
    token too; a bearer-token-authenticated one doesn't.

    Args:
        x_csrf_token (str | Unset):
        body (AddConsumerRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ConsumerEntry | Error]
    """

    kwargs = _get_kwargs(
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: AddConsumerRequest,
    x_csrf_token: str | Unset = UNSET,
) -> ConsumerEntry | Error | None:
    """Add a consumer with no secret referencing it yet

     Adds `name` to the directory (`alrayyes/hush-hush#324`) without
    requiring any object's `used_by` list to reference it first -
    unlike every other consumer here, which only ever exist because
    some object's `used_by` recorded them. The new entry appears in
    `GET /consumers` with a `secret_count` of 0 until something
    actually uses it. A session-authenticated call needs its CSRF
    token too; a bearer-token-authenticated one doesn't.

    Args:
        x_csrf_token (str | Unset):
        body (AddConsumerRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ConsumerEntry | Error
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
            x_csrf_token=x_csrf_token,
        )
    ).parsed
