# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...types import UNSET, Response, Unset


def _get_kwargs(
    name: str,
    *,
    x_csrf_token: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_csrf_token, Unset):
        headers["X-CSRF-Token"] = x_csrf_token

    _kwargs: dict[str, Any] = {
        "method": "delete",
        "url": "/consumers/{name}".format(
            name=quote(str(name), safe=""),
        ),
    }

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Any | Error | None:
    if response.status_code == 204:
        response_204 = cast(Any, None)
        return response_204

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Any | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    name: str,
    *,
    client: AuthenticatedClient,
    x_csrf_token: str | Unset = UNSET,
) -> Response[Any | Error]:
    """Remove a consumer from every object that references it

     Strips `name` from the `used_by` list of every stored object that
    currently records it - the objects themselves aren't touched
    otherwise, and none are deleted even if this empties their
    `used_by` list. A subsequent `GET /consumers` no longer lists this
    name. A session-authenticated call needs its CSRF token too; a
    bearer-token-authenticated one doesn't.

    Args:
        name (str):
        x_csrf_token (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | Error]
    """

    kwargs = _get_kwargs(
        name=name,
        x_csrf_token=x_csrf_token,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    name: str,
    *,
    client: AuthenticatedClient,
    x_csrf_token: str | Unset = UNSET,
) -> Any | Error | None:
    """Remove a consumer from every object that references it

     Strips `name` from the `used_by` list of every stored object that
    currently records it - the objects themselves aren't touched
    otherwise, and none are deleted even if this empties their
    `used_by` list. A subsequent `GET /consumers` no longer lists this
    name. A session-authenticated call needs its CSRF token too; a
    bearer-token-authenticated one doesn't.

    Args:
        name (str):
        x_csrf_token (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | Error
    """

    return sync_detailed(
        name=name,
        client=client,
        x_csrf_token=x_csrf_token,
    ).parsed


async def asyncio_detailed(
    name: str,
    *,
    client: AuthenticatedClient,
    x_csrf_token: str | Unset = UNSET,
) -> Response[Any | Error]:
    """Remove a consumer from every object that references it

     Strips `name` from the `used_by` list of every stored object that
    currently records it - the objects themselves aren't touched
    otherwise, and none are deleted even if this empties their
    `used_by` list. A subsequent `GET /consumers` no longer lists this
    name. A session-authenticated call needs its CSRF token too; a
    bearer-token-authenticated one doesn't.

    Args:
        name (str):
        x_csrf_token (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | Error]
    """

    kwargs = _get_kwargs(
        name=name,
        x_csrf_token=x_csrf_token,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    name: str,
    *,
    client: AuthenticatedClient,
    x_csrf_token: str | Unset = UNSET,
) -> Any | Error | None:
    """Remove a consumer from every object that references it

     Strips `name` from the `used_by` list of every stored object that
    currently records it - the objects themselves aren't touched
    otherwise, and none are deleted even if this empties their
    `used_by` list. A subsequent `GET /consumers` no longer lists this
    name. A session-authenticated call needs its CSRF token too; a
    bearer-token-authenticated one doesn't.

    Args:
        name (str):
        x_csrf_token (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | Error
    """

    return (
        await asyncio_detailed(
            name=name,
            client=client,
            x_csrf_token=x_csrf_token,
        )
    ).parsed
