# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.consumer_entry import ConsumerEntry
from ...models.error import Error
from ...models.update_consumer_request import UpdateConsumerRequest
from ...types import UNSET, Response, Unset


def _get_kwargs(
    name: str,
    *,
    body: UpdateConsumerRequest,
    x_csrf_token: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_csrf_token, Unset):
        headers["X-CSRF-Token"] = x_csrf_token

    _kwargs: dict[str, Any] = {
        "method": "patch",
        "url": "/consumers/{name}".format(
            name=quote(str(name), safe=""),
        ),
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> ConsumerEntry | Error | None:
    if response.status_code == 200:
        response_200 = ConsumerEntry.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 413:
        response_413 = Error.from_dict(response.json())

        return response_413

    if response.status_code == 422:
        response_422 = Error.from_dict(response.json())

        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[ConsumerEntry | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    name: str,
    *,
    client: AuthenticatedClient,
    body: UpdateConsumerRequest,
    x_csrf_token: str | Unset = UNSET,
) -> Response[ConsumerEntry | Error]:
    """Rename a consumer and/or register its public key

     Consumers aren't a stored resource of their own (`alrayyes/hush-hush#282`,
    following ADR 0002's deferred consumer-identity decision) - a
    `name` in the request body replaces `name` in every stored
    object's `used_by` list that currently records it, the same as
    before this endpoint also took `public_key`. An object already
    recording the target name keeps a single entry, not a duplicate.
    If the target name already has its own recorded objects, they
    merge under it: the response's `secret_count` reflects every
    object now recording the new name, old and already-there
    combined. Renaming an unknown name is rejected with a 404.

    A `public_key` in the request body registers or replaces that age
    public key on the (possibly just-renamed) consumer, upserting a
    directory entry for it even if it had none before - unlike a bare
    rename, this never 404s on an unrecognized name. Sending both
    fields in the same call renames first, then sets the key on the
    resulting name.

    A session-authenticated call needs its CSRF token too; a
    bearer-token-authenticated one doesn't.

    Args:
        name (str):
        x_csrf_token (str | Unset):
        body (UpdateConsumerRequest): At least one of `name` or `public_key` is required (enforced
            by
            `minProperties` above); a field left out leaves that aspect of the
            consumer unchanged. There is no way to clear a registered public
            key through this request, only to set or replace one.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ConsumerEntry | Error]
    """

    kwargs = _get_kwargs(
        name=name,
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    name: str,
    *,
    client: AuthenticatedClient,
    body: UpdateConsumerRequest,
    x_csrf_token: str | Unset = UNSET,
) -> ConsumerEntry | Error | None:
    """Rename a consumer and/or register its public key

     Consumers aren't a stored resource of their own (`alrayyes/hush-hush#282`,
    following ADR 0002's deferred consumer-identity decision) - a
    `name` in the request body replaces `name` in every stored
    object's `used_by` list that currently records it, the same as
    before this endpoint also took `public_key`. An object already
    recording the target name keeps a single entry, not a duplicate.
    If the target name already has its own recorded objects, they
    merge under it: the response's `secret_count` reflects every
    object now recording the new name, old and already-there
    combined. Renaming an unknown name is rejected with a 404.

    A `public_key` in the request body registers or replaces that age
    public key on the (possibly just-renamed) consumer, upserting a
    directory entry for it even if it had none before - unlike a bare
    rename, this never 404s on an unrecognized name. Sending both
    fields in the same call renames first, then sets the key on the
    resulting name.

    A session-authenticated call needs its CSRF token too; a
    bearer-token-authenticated one doesn't.

    Args:
        name (str):
        x_csrf_token (str | Unset):
        body (UpdateConsumerRequest): At least one of `name` or `public_key` is required (enforced
            by
            `minProperties` above); a field left out leaves that aspect of the
            consumer unchanged. There is no way to clear a registered public
            key through this request, only to set or replace one.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ConsumerEntry | Error
    """

    return sync_detailed(
        name=name,
        client=client,
        body=body,
        x_csrf_token=x_csrf_token,
    ).parsed


async def asyncio_detailed(
    name: str,
    *,
    client: AuthenticatedClient,
    body: UpdateConsumerRequest,
    x_csrf_token: str | Unset = UNSET,
) -> Response[ConsumerEntry | Error]:
    """Rename a consumer and/or register its public key

     Consumers aren't a stored resource of their own (`alrayyes/hush-hush#282`,
    following ADR 0002's deferred consumer-identity decision) - a
    `name` in the request body replaces `name` in every stored
    object's `used_by` list that currently records it, the same as
    before this endpoint also took `public_key`. An object already
    recording the target name keeps a single entry, not a duplicate.
    If the target name already has its own recorded objects, they
    merge under it: the response's `secret_count` reflects every
    object now recording the new name, old and already-there
    combined. Renaming an unknown name is rejected with a 404.

    A `public_key` in the request body registers or replaces that age
    public key on the (possibly just-renamed) consumer, upserting a
    directory entry for it even if it had none before - unlike a bare
    rename, this never 404s on an unrecognized name. Sending both
    fields in the same call renames first, then sets the key on the
    resulting name.

    A session-authenticated call needs its CSRF token too; a
    bearer-token-authenticated one doesn't.

    Args:
        name (str):
        x_csrf_token (str | Unset):
        body (UpdateConsumerRequest): At least one of `name` or `public_key` is required (enforced
            by
            `minProperties` above); a field left out leaves that aspect of the
            consumer unchanged. There is no way to clear a registered public
            key through this request, only to set or replace one.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ConsumerEntry | Error]
    """

    kwargs = _get_kwargs(
        name=name,
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    name: str,
    *,
    client: AuthenticatedClient,
    body: UpdateConsumerRequest,
    x_csrf_token: str | Unset = UNSET,
) -> ConsumerEntry | Error | None:
    """Rename a consumer and/or register its public key

     Consumers aren't a stored resource of their own (`alrayyes/hush-hush#282`,
    following ADR 0002's deferred consumer-identity decision) - a
    `name` in the request body replaces `name` in every stored
    object's `used_by` list that currently records it, the same as
    before this endpoint also took `public_key`. An object already
    recording the target name keeps a single entry, not a duplicate.
    If the target name already has its own recorded objects, they
    merge under it: the response's `secret_count` reflects every
    object now recording the new name, old and already-there
    combined. Renaming an unknown name is rejected with a 404.

    A `public_key` in the request body registers or replaces that age
    public key on the (possibly just-renamed) consumer, upserting a
    directory entry for it even if it had none before - unlike a bare
    rename, this never 404s on an unrecognized name. Sending both
    fields in the same call renames first, then sets the key on the
    resulting name.

    A session-authenticated call needs its CSRF token too; a
    bearer-token-authenticated one doesn't.

    Args:
        name (str):
        x_csrf_token (str | Unset):
        body (UpdateConsumerRequest): At least one of `name` or `public_key` is required (enforced
            by
            `minProperties` above); a field left out leaves that aspect of the
            consumer unchanged. There is no way to clear a registered public
            key through this request, only to set or replace one.

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ConsumerEntry | Error
    """

    return (
        await asyncio_detailed(
            name=name,
            client=client,
            body=body,
            x_csrf_token=x_csrf_token,
        )
    ).parsed
