# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.create_object_request import CreateObjectRequest
from ...models.error import Error
from ...models.object_metadata import ObjectMetadata
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    body: CreateObjectRequest,
    x_caller: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_caller, Unset):
        headers["X-Caller"] = x_caller

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/objects",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | ObjectMetadata | None:
    if response.status_code == 201:
        response_201 = ObjectMetadata.from_dict(response.json())

        return response_201

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 409:
        response_409 = Error.from_dict(response.json())

        return response_409

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | ObjectMetadata]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: CreateObjectRequest,
    x_caller: str | Unset = UNSET,
) -> Response[Error | ObjectMetadata]:
    """Create a new sealed object

     Stores an already-sealed value under a new object id. The value is
    opaque ciphertext to this service - it is never decrypted, and the
    service has no notion of which recipients it was sealed to.

    Args:
        x_caller (str | Unset):
        body (CreateObjectRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ObjectMetadata]
    """

    kwargs = _get_kwargs(
        body=body,
        x_caller=x_caller,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: CreateObjectRequest,
    x_caller: str | Unset = UNSET,
) -> Error | ObjectMetadata | None:
    """Create a new sealed object

     Stores an already-sealed value under a new object id. The value is
    opaque ciphertext to this service - it is never decrypted, and the
    service has no notion of which recipients it was sealed to.

    Args:
        x_caller (str | Unset):
        body (CreateObjectRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ObjectMetadata
    """

    return sync_detailed(
        client=client,
        body=body,
        x_caller=x_caller,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: CreateObjectRequest,
    x_caller: str | Unset = UNSET,
) -> Response[Error | ObjectMetadata]:
    """Create a new sealed object

     Stores an already-sealed value under a new object id. The value is
    opaque ciphertext to this service - it is never decrypted, and the
    service has no notion of which recipients it was sealed to.

    Args:
        x_caller (str | Unset):
        body (CreateObjectRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ObjectMetadata]
    """

    kwargs = _get_kwargs(
        body=body,
        x_caller=x_caller,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: CreateObjectRequest,
    x_caller: str | Unset = UNSET,
) -> Error | ObjectMetadata | None:
    """Create a new sealed object

     Stores an already-sealed value under a new object id. The value is
    opaque ciphertext to this service - it is never decrypted, and the
    service has no notion of which recipients it was sealed to.

    Args:
        x_caller (str | Unset):
        body (CreateObjectRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ObjectMetadata
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
            x_caller=x_caller,
        )
    ).parsed
