# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from io import BytesIO
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...types import UNSET, File, Response, Unset


def _get_kwargs(
    id: str,
    *,
    x_caller: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_caller, Unset):
        headers["X-Caller"] = x_caller

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/objects/{id}".format(
            id=quote(str(id), safe=""),
        ),
    }

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | File | None:
    if response.status_code == 200:
        response_200 = File(payload=BytesIO(response.content))

        return response_200

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | File]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    id: str,
    *,
    client: AuthenticatedClient | Client,
    x_caller: str | Unset = UNSET,
) -> Response[Error | File]:
    r"""Fetch an object's sealed ciphertext

     Returns the stored ciphertext exactly as sealed, byte for byte -
    the service never decrypts it. Needs no authorization beyond
    knowing the id: v1's confidentiality boundary is entirely \"who
    holds a matching private key,\" and every fetch is recorded to the
    audit log regardless of who made it.

    Args:
        id (str):
        x_caller (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | File]
    """

    kwargs = _get_kwargs(
        id=id,
        x_caller=x_caller,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    id: str,
    *,
    client: AuthenticatedClient | Client,
    x_caller: str | Unset = UNSET,
) -> Error | File | None:
    r"""Fetch an object's sealed ciphertext

     Returns the stored ciphertext exactly as sealed, byte for byte -
    the service never decrypts it. Needs no authorization beyond
    knowing the id: v1's confidentiality boundary is entirely \"who
    holds a matching private key,\" and every fetch is recorded to the
    audit log regardless of who made it.

    Args:
        id (str):
        x_caller (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | File
    """

    return sync_detailed(
        id=id,
        client=client,
        x_caller=x_caller,
    ).parsed


async def asyncio_detailed(
    id: str,
    *,
    client: AuthenticatedClient | Client,
    x_caller: str | Unset = UNSET,
) -> Response[Error | File]:
    r"""Fetch an object's sealed ciphertext

     Returns the stored ciphertext exactly as sealed, byte for byte -
    the service never decrypts it. Needs no authorization beyond
    knowing the id: v1's confidentiality boundary is entirely \"who
    holds a matching private key,\" and every fetch is recorded to the
    audit log regardless of who made it.

    Args:
        id (str):
        x_caller (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | File]
    """

    kwargs = _get_kwargs(
        id=id,
        x_caller=x_caller,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    id: str,
    *,
    client: AuthenticatedClient | Client,
    x_caller: str | Unset = UNSET,
) -> Error | File | None:
    r"""Fetch an object's sealed ciphertext

     Returns the stored ciphertext exactly as sealed, byte for byte -
    the service never decrypts it. Needs no authorization beyond
    knowing the id: v1's confidentiality boundary is entirely \"who
    holds a matching private key,\" and every fetch is recorded to the
    audit log regardless of who made it.

    Args:
        id (str):
        x_caller (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | File
    """

    return (
        await asyncio_detailed(
            id=id,
            client=client,
            x_caller=x_caller,
        )
    ).parsed
