# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any
from urllib.parse import quote
from uuid import UUID

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.used_by import UsedBy
from ...types import UNSET, Response, Unset


def _get_kwargs(
    slug: str,
    *,
    id: UUID | Unset = UNSET,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    json_id: str | Unset = UNSET
    if not isinstance(id, Unset):
        json_id = str(id)
    params["id"] = json_id

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/objects/{slug}/used-by".format(
            slug=quote(str(slug), safe=""),
        ),
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | UsedBy | None:
    if response.status_code == 200:
        response_200 = UsedBy.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 409:
        response_409 = Error.from_dict(response.json())

        return response_409

    if response.status_code == 422:
        response_422 = Error.from_dict(response.json())

        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | UsedBy]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    slug: str,
    *,
    client: AuthenticatedClient | Client,
    id: UUID | Unset = UNSET,
) -> Response[Error | UsedBy]:
    """Query what depends on an object

     Returns the recorded list of consumers (repos or hosts) for an
    object - the "what depends on this" mapping, kept queryable rather
    than left as an implied convention.

    Args:
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        id (UUID | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | UsedBy]
    """

    kwargs = _get_kwargs(
        slug=slug,
        id=id,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    slug: str,
    *,
    client: AuthenticatedClient | Client,
    id: UUID | Unset = UNSET,
) -> Error | UsedBy | None:
    """Query what depends on an object

     Returns the recorded list of consumers (repos or hosts) for an
    object - the "what depends on this" mapping, kept queryable rather
    than left as an implied convention.

    Args:
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        id (UUID | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | UsedBy
    """

    return sync_detailed(
        slug=slug,
        client=client,
        id=id,
    ).parsed


async def asyncio_detailed(
    slug: str,
    *,
    client: AuthenticatedClient | Client,
    id: UUID | Unset = UNSET,
) -> Response[Error | UsedBy]:
    """Query what depends on an object

     Returns the recorded list of consumers (repos or hosts) for an
    object - the "what depends on this" mapping, kept queryable rather
    than left as an implied convention.

    Args:
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        id (UUID | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | UsedBy]
    """

    kwargs = _get_kwargs(
        slug=slug,
        id=id,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    slug: str,
    *,
    client: AuthenticatedClient | Client,
    id: UUID | Unset = UNSET,
) -> Error | UsedBy | None:
    """Query what depends on an object

     Returns the recorded list of consumers (repos or hosts) for an
    object - the "what depends on this" mapping, kept queryable rather
    than left as an implied convention.

    Args:
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        id (UUID | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | UsedBy
    """

    return (
        await asyncio_detailed(
            slug=slug,
            client=client,
            id=id,
        )
    ).parsed
