# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from io import BytesIO
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...types import UNSET, File, Response, Unset


def _get_kwargs(
    slug: str,
    *,
    x_caller: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_caller, Unset):
        headers["X-Caller"] = x_caller

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/objects/{slug}".format(
            slug=quote(str(slug), safe=""),
        ),
    }

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | File | None:
    if response.status_code == 200:
        response_200 = File(payload=BytesIO(response.content))

        return response_200

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 422:
        response_422 = Error.from_dict(response.json())

        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | File]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    slug: str,
    *,
    client: AuthenticatedClient,
    x_caller: str | Unset = UNSET,
) -> Response[Error | File]:
    """Fetch an object's sealed ciphertext

     Returns the stored ciphertext exactly as sealed, byte for byte -
    the service never decrypts it. Requires a write bearer token, an
    admin session, or a consumer read token whose bound consumer
    appears in this object's `used_by` list - the confidentiality
    boundary is still "who holds a matching private key," this adds
    an access-control layer on top of it
    (openspec/changes/consumer-read-tokens/proposal.md). Every fetch
    is recorded to the audit log regardless of which credential
    authenticated it.

    A consumer token presented for an object outside its scope gets
    the same 404 an unknown slug would, not 403 - so it can't be used
    to enumerate which other slugs exist.

    Args:
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        x_caller (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | File]
    """

    kwargs = _get_kwargs(
        slug=slug,
        x_caller=x_caller,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    slug: str,
    *,
    client: AuthenticatedClient,
    x_caller: str | Unset = UNSET,
) -> Error | File | None:
    """Fetch an object's sealed ciphertext

     Returns the stored ciphertext exactly as sealed, byte for byte -
    the service never decrypts it. Requires a write bearer token, an
    admin session, or a consumer read token whose bound consumer
    appears in this object's `used_by` list - the confidentiality
    boundary is still "who holds a matching private key," this adds
    an access-control layer on top of it
    (openspec/changes/consumer-read-tokens/proposal.md). Every fetch
    is recorded to the audit log regardless of which credential
    authenticated it.

    A consumer token presented for an object outside its scope gets
    the same 404 an unknown slug would, not 403 - so it can't be used
    to enumerate which other slugs exist.

    Args:
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        x_caller (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | File
    """

    return sync_detailed(
        slug=slug,
        client=client,
        x_caller=x_caller,
    ).parsed


async def asyncio_detailed(
    slug: str,
    *,
    client: AuthenticatedClient,
    x_caller: str | Unset = UNSET,
) -> Response[Error | File]:
    """Fetch an object's sealed ciphertext

     Returns the stored ciphertext exactly as sealed, byte for byte -
    the service never decrypts it. Requires a write bearer token, an
    admin session, or a consumer read token whose bound consumer
    appears in this object's `used_by` list - the confidentiality
    boundary is still "who holds a matching private key," this adds
    an access-control layer on top of it
    (openspec/changes/consumer-read-tokens/proposal.md). Every fetch
    is recorded to the audit log regardless of which credential
    authenticated it.

    A consumer token presented for an object outside its scope gets
    the same 404 an unknown slug would, not 403 - so it can't be used
    to enumerate which other slugs exist.

    Args:
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        x_caller (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | File]
    """

    kwargs = _get_kwargs(
        slug=slug,
        x_caller=x_caller,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    slug: str,
    *,
    client: AuthenticatedClient,
    x_caller: str | Unset = UNSET,
) -> Error | File | None:
    """Fetch an object's sealed ciphertext

     Returns the stored ciphertext exactly as sealed, byte for byte -
    the service never decrypts it. Requires a write bearer token, an
    admin session, or a consumer read token whose bound consumer
    appears in this object's `used_by` list - the confidentiality
    boundary is still "who holds a matching private key," this adds
    an access-control layer on top of it
    (openspec/changes/consumer-read-tokens/proposal.md). Every fetch
    is recorded to the audit log regardless of which credential
    authenticated it.

    A consumer token presented for an object outside its scope gets
    the same 404 an unknown slug would, not 403 - so it can't be used
    to enumerate which other slugs exist.

    Args:
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        x_caller (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | File
    """

    return (
        await asyncio_detailed(
            slug=slug,
            client=client,
            x_caller=x_caller,
        )
    ).parsed
