# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.object_metadata import ObjectMetadata
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    used_by: str | Unset = UNSET,
    tag: list[str] | Unset = UNSET,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["used_by"] = used_by

    json_tag: list[str] | Unset = UNSET
    if not isinstance(tag, Unset):
        json_tag = tag

    params["tag"] = json_tag

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/objects",
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | list[ObjectMetadata] | None:
    if response.status_code == 200:
        response_200 = []
        _response_200 = response.json()
        for response_200_item_data in _response_200:
            response_200_item = ObjectMetadata.from_dict(response_200_item_data)

            response_200.append(response_200_item)

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 422:
        response_422 = Error.from_dict(response.json())

        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | list[ObjectMetadata]]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    used_by: str | Unset = UNSET,
    tag: list[str] | Unset = UNSET,
) -> Response[Error | list[ObjectMetadata]]:
    """List stored objects

     Returns every stored object's metadata (slug, used_by, tags,
    description, and who created and last updated it and when) - never
    the sealed value, and never the internal id as something
    addressable. Gated by a write token or a session unlike every
    other read path here: a slug-scoped read only ever discloses what
    a caller already knows the slug of, but enumerating every object
    is a capability none of those reads grant on their own. The web UI
    holds a session, never a bearer token, and uses this for its
    secrets overview - the two credentials are equally valid here
    (auth/spec.md's "A session authenticates secret-object access"
    requirement).

    Args:
        used_by (str | Unset):
        tag (list[str] | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | list[ObjectMetadata]]
    """

    kwargs = _get_kwargs(
        used_by=used_by,
        tag=tag,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    used_by: str | Unset = UNSET,
    tag: list[str] | Unset = UNSET,
) -> Error | list[ObjectMetadata] | None:
    """List stored objects

     Returns every stored object's metadata (slug, used_by, tags,
    description, and who created and last updated it and when) - never
    the sealed value, and never the internal id as something
    addressable. Gated by a write token or a session unlike every
    other read path here: a slug-scoped read only ever discloses what
    a caller already knows the slug of, but enumerating every object
    is a capability none of those reads grant on their own. The web UI
    holds a session, never a bearer token, and uses this for its
    secrets overview - the two credentials are equally valid here
    (auth/spec.md's "A session authenticates secret-object access"
    requirement).

    Args:
        used_by (str | Unset):
        tag (list[str] | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | list[ObjectMetadata]
    """

    return sync_detailed(
        client=client,
        used_by=used_by,
        tag=tag,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    used_by: str | Unset = UNSET,
    tag: list[str] | Unset = UNSET,
) -> Response[Error | list[ObjectMetadata]]:
    """List stored objects

     Returns every stored object's metadata (slug, used_by, tags,
    description, and who created and last updated it and when) - never
    the sealed value, and never the internal id as something
    addressable. Gated by a write token or a session unlike every
    other read path here: a slug-scoped read only ever discloses what
    a caller already knows the slug of, but enumerating every object
    is a capability none of those reads grant on their own. The web UI
    holds a session, never a bearer token, and uses this for its
    secrets overview - the two credentials are equally valid here
    (auth/spec.md's "A session authenticates secret-object access"
    requirement).

    Args:
        used_by (str | Unset):
        tag (list[str] | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | list[ObjectMetadata]]
    """

    kwargs = _get_kwargs(
        used_by=used_by,
        tag=tag,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    used_by: str | Unset = UNSET,
    tag: list[str] | Unset = UNSET,
) -> Error | list[ObjectMetadata] | None:
    """List stored objects

     Returns every stored object's metadata (slug, used_by, tags,
    description, and who created and last updated it and when) - never
    the sealed value, and never the internal id as something
    addressable. Gated by a write token or a session unlike every
    other read path here: a slug-scoped read only ever discloses what
    a caller already knows the slug of, but enumerating every object
    is a capability none of those reads grant on their own. The web UI
    holds a session, never a bearer token, and uses this for its
    secrets overview - the two credentials are equally valid here
    (auth/spec.md's "A session authenticates secret-object access"
    requirement).

    Args:
        used_by (str | Unset):
        tag (list[str] | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | list[ObjectMetadata]
    """

    return (
        await asyncio_detailed(
            client=client,
            used_by=used_by,
            tag=tag,
        )
    ).parsed
