# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.object_metadata import ObjectMetadata
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    used_by: str | Unset = UNSET,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["used_by"] = used_by

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/objects",
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | list[ObjectMetadata] | None:
    if response.status_code == 200:
        response_200 = []
        _response_200 = response.json()
        for response_200_item_data in _response_200:
            response_200_item = ObjectMetadata.from_dict(response_200_item_data)

            response_200.append(response_200_item)

        return response_200

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | list[ObjectMetadata]]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    used_by: str | Unset = UNSET,
) -> Response[Error | list[ObjectMetadata]]:
    """List stored objects

     Returns every stored object's metadata (id, used_by, description) -
    never the sealed value. Gated by a write token unlike every other
    read path here: an id-scoped read only ever discloses what a
    caller already knows the id of, but enumerating every object is a
    capability none of those reads grant on their own.

    Args:
        used_by (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | list[ObjectMetadata]]
    """

    kwargs = _get_kwargs(
        used_by=used_by,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    used_by: str | Unset = UNSET,
) -> Error | list[ObjectMetadata] | None:
    """List stored objects

     Returns every stored object's metadata (id, used_by, description) -
    never the sealed value. Gated by a write token unlike every other
    read path here: an id-scoped read only ever discloses what a
    caller already knows the id of, but enumerating every object is a
    capability none of those reads grant on their own.

    Args:
        used_by (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | list[ObjectMetadata]
    """

    return sync_detailed(
        client=client,
        used_by=used_by,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    used_by: str | Unset = UNSET,
) -> Response[Error | list[ObjectMetadata]]:
    """List stored objects

     Returns every stored object's metadata (id, used_by, description) -
    never the sealed value. Gated by a write token unlike every other
    read path here: an id-scoped read only ever discloses what a
    caller already knows the id of, but enumerating every object is a
    capability none of those reads grant on their own.

    Args:
        used_by (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | list[ObjectMetadata]]
    """

    kwargs = _get_kwargs(
        used_by=used_by,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    used_by: str | Unset = UNSET,
) -> Error | list[ObjectMetadata] | None:
    """List stored objects

     Returns every stored object's metadata (id, used_by, description) -
    never the sealed value. Gated by a write token unlike every other
    read path here: an id-scoped read only ever discloses what a
    caller already knows the id of, but enumerating every object is a
    capability none of those reads grant on their own.

    Args:
        used_by (str | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | list[ObjectMetadata]
    """

    return (
        await asyncio_detailed(
            client=client,
            used_by=used_by,
        )
    ).parsed
