# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.object_metadata import ObjectMetadata
from ...models.update_object_request import UpdateObjectRequest
from ...types import UNSET, Response, Unset


def _get_kwargs(
    slug: str,
    *,
    body: UpdateObjectRequest,
    x_caller: str | Unset = UNSET,
    x_csrf_token: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_caller, Unset):
        headers["X-Caller"] = x_caller

    if not isinstance(x_csrf_token, Unset):
        headers["X-CSRF-Token"] = x_csrf_token

    _kwargs: dict[str, Any] = {
        "method": "put",
        "url": "/objects/{slug}".format(
            slug=quote(str(slug), safe=""),
        ),
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | ObjectMetadata | None:
    if response.status_code == 200:
        response_200 = ObjectMetadata.from_dict(response.json())

        return response_200

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 413:
        response_413 = Error.from_dict(response.json())

        return response_413

    if response.status_code == 422:
        response_422 = Error.from_dict(response.json())

        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | ObjectMetadata]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    slug: str,
    *,
    client: AuthenticatedClient,
    body: UpdateObjectRequest,
    x_caller: str | Unset = UNSET,
    x_csrf_token: str | Unset = UNSET,
) -> Response[Error | ObjectMetadata]:
    """Rotate an object's value

     Replaces the stored ciphertext for an existing object. The new
    value is checked the same way a created one is: not base64 of a
    well-formed age file, or no recipient in its header, is a 422
    and the stored value is left alone. The
    object's slug and description metadata are always preserved
    unchanged. used_by is preserved too, unless the request body
    includes it - in which case it fully replaces the object's
    recorded consumers, the same way creating an object sets it. A
    session-authenticated call needs its CSRF token too; a
    bearer-token-authenticated one doesn't.

    Args:
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        x_caller (str | Unset):
        x_csrf_token (str | Unset):
        body (UpdateObjectRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ObjectMetadata]
    """

    kwargs = _get_kwargs(
        slug=slug,
        body=body,
        x_caller=x_caller,
        x_csrf_token=x_csrf_token,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    slug: str,
    *,
    client: AuthenticatedClient,
    body: UpdateObjectRequest,
    x_caller: str | Unset = UNSET,
    x_csrf_token: str | Unset = UNSET,
) -> Error | ObjectMetadata | None:
    """Rotate an object's value

     Replaces the stored ciphertext for an existing object. The new
    value is checked the same way a created one is: not base64 of a
    well-formed age file, or no recipient in its header, is a 422
    and the stored value is left alone. The
    object's slug and description metadata are always preserved
    unchanged. used_by is preserved too, unless the request body
    includes it - in which case it fully replaces the object's
    recorded consumers, the same way creating an object sets it. A
    session-authenticated call needs its CSRF token too; a
    bearer-token-authenticated one doesn't.

    Args:
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        x_caller (str | Unset):
        x_csrf_token (str | Unset):
        body (UpdateObjectRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ObjectMetadata
    """

    return sync_detailed(
        slug=slug,
        client=client,
        body=body,
        x_caller=x_caller,
        x_csrf_token=x_csrf_token,
    ).parsed


async def asyncio_detailed(
    slug: str,
    *,
    client: AuthenticatedClient,
    body: UpdateObjectRequest,
    x_caller: str | Unset = UNSET,
    x_csrf_token: str | Unset = UNSET,
) -> Response[Error | ObjectMetadata]:
    """Rotate an object's value

     Replaces the stored ciphertext for an existing object. The new
    value is checked the same way a created one is: not base64 of a
    well-formed age file, or no recipient in its header, is a 422
    and the stored value is left alone. The
    object's slug and description metadata are always preserved
    unchanged. used_by is preserved too, unless the request body
    includes it - in which case it fully replaces the object's
    recorded consumers, the same way creating an object sets it. A
    session-authenticated call needs its CSRF token too; a
    bearer-token-authenticated one doesn't.

    Args:
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        x_caller (str | Unset):
        x_csrf_token (str | Unset):
        body (UpdateObjectRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ObjectMetadata]
    """

    kwargs = _get_kwargs(
        slug=slug,
        body=body,
        x_caller=x_caller,
        x_csrf_token=x_csrf_token,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    slug: str,
    *,
    client: AuthenticatedClient,
    body: UpdateObjectRequest,
    x_caller: str | Unset = UNSET,
    x_csrf_token: str | Unset = UNSET,
) -> Error | ObjectMetadata | None:
    """Rotate an object's value

     Replaces the stored ciphertext for an existing object. The new
    value is checked the same way a created one is: not base64 of a
    well-formed age file, or no recipient in its header, is a 422
    and the stored value is left alone. The
    object's slug and description metadata are always preserved
    unchanged. used_by is preserved too, unless the request body
    includes it - in which case it fully replaces the object's
    recorded consumers, the same way creating an object sets it. A
    session-authenticated call needs its CSRF token too; a
    bearer-token-authenticated one doesn't.

    Args:
        slug (str): A caller-chosen, unique identifier for an object - what every
            documented request path (URL, CLI, API) addresses it by. The
            object's internal id is a separate, opaque value never exposed to
            or accepted from a caller (specs/secret-objects/spec.md's
            "Internal id decoupled from user-facing slug" requirement).
        x_caller (str | Unset):
        x_csrf_token (str | Unset):
        body (UpdateObjectRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ObjectMetadata
    """

    return (
        await asyncio_detailed(
            slug=slug,
            client=client,
            body=body,
            x_caller=x_caller,
            x_csrf_token=x_csrf_token,
        )
    ).parsed
