# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.object_metadata import ObjectMetadata
from ...models.update_object_request import UpdateObjectRequest
from ...types import UNSET, Response, Unset


def _get_kwargs(
    id: str,
    *,
    body: UpdateObjectRequest,
    x_caller: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_caller, Unset):
        headers["X-Caller"] = x_caller

    _kwargs: dict[str, Any] = {
        "method": "put",
        "url": "/objects/{id}".format(
            id=quote(str(id), safe=""),
        ),
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | ObjectMetadata | None:
    if response.status_code == 200:
        response_200 = ObjectMetadata.from_dict(response.json())

        return response_200

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | ObjectMetadata]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    id: str,
    *,
    client: AuthenticatedClient,
    body: UpdateObjectRequest,
    x_caller: str | Unset = UNSET,
) -> Response[Error | ObjectMetadata]:
    """Rotate an object's value

     Replaces the stored ciphertext for an existing object. The
    object's id and used_by metadata are preserved unchanged - this
    endpoint only ever touches the value.

    Args:
        id (str):
        x_caller (str | Unset):
        body (UpdateObjectRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ObjectMetadata]
    """

    kwargs = _get_kwargs(
        id=id,
        body=body,
        x_caller=x_caller,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    id: str,
    *,
    client: AuthenticatedClient,
    body: UpdateObjectRequest,
    x_caller: str | Unset = UNSET,
) -> Error | ObjectMetadata | None:
    """Rotate an object's value

     Replaces the stored ciphertext for an existing object. The
    object's id and used_by metadata are preserved unchanged - this
    endpoint only ever touches the value.

    Args:
        id (str):
        x_caller (str | Unset):
        body (UpdateObjectRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ObjectMetadata
    """

    return sync_detailed(
        id=id,
        client=client,
        body=body,
        x_caller=x_caller,
    ).parsed


async def asyncio_detailed(
    id: str,
    *,
    client: AuthenticatedClient,
    body: UpdateObjectRequest,
    x_caller: str | Unset = UNSET,
) -> Response[Error | ObjectMetadata]:
    """Rotate an object's value

     Replaces the stored ciphertext for an existing object. The
    object's id and used_by metadata are preserved unchanged - this
    endpoint only ever touches the value.

    Args:
        id (str):
        x_caller (str | Unset):
        body (UpdateObjectRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | ObjectMetadata]
    """

    kwargs = _get_kwargs(
        id=id,
        body=body,
        x_caller=x_caller,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    id: str,
    *,
    client: AuthenticatedClient,
    body: UpdateObjectRequest,
    x_caller: str | Unset = UNSET,
) -> Error | ObjectMetadata | None:
    """Rotate an object's value

     Replaces the stored ciphertext for an existing object. The
    object's id and used_by metadata are preserved unchanged - this
    endpoint only ever touches the value.

    Args:
        id (str):
        x_caller (str | Unset):
        body (UpdateObjectRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | ObjectMetadata
    """

    return (
        await asyncio_detailed(
            id=id,
            client=client,
            body=body,
            x_caller=x_caller,
        )
    ).parsed
