#!/usr/bin/env bash
# Regenerates src/hush_hush/_generated from the pinned hush-hush spec
# submodule. openapi-python-client doesn't stamp a generated-code header of
# its own, so this adds one to every file it writes — that's what
# CONTRIBUTING.md's DO-NOT-EDIT boundary and ci.yml's codegen-drift check
# actually depend on existing.
set -euo pipefail

cd "$(dirname "$0")/.."

rm -rf src/hush_hush/_generated
uv run openapi-python-client generate \
  --path hush-hush/api/openapi.yaml \
  --meta none \
  --output-path src/hush_hush/_generated \
  --overwrite

header="# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT."
find src/hush_hush/_generated -name "*.py" -print0 | while IFS= read -r -d '' file; do
  { echo "$header"; echo; cat "$file"; } > "$file.tmp"
  mv "$file.tmp" "$file"
done

uv run ruff format src/hush_hush/_generated
uv run ruff check --fix --unsafe-fixes src/hush_hush/_generated >/dev/null || true
