# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.credential import Credential
from ...models.credential_rename_request import CredentialRenameRequest
from ...models.error import Error
from ...types import Response


def _get_kwargs(
    id: str,
    *,
    body: CredentialRenameRequest,
    x_csrf_token: str,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    headers["X-CSRF-Token"] = x_csrf_token

    _kwargs: dict[str, Any] = {
        "method": "patch",
        "url": "/credentials/{id}".format(
            id=quote(str(id), safe=""),
        ),
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Credential | Error | None:
    if response.status_code == 200:
        response_200 = Credential.from_dict(response.json())

        return response_200

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Credential | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    id: str,
    *,
    client: AuthenticatedClient,
    body: CredentialRenameRequest,
    x_csrf_token: str,
) -> Response[Credential | Error]:
    """Rename a passkey

    Args:
        id (str):
        x_csrf_token (str):
        body (CredentialRenameRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Credential | Error]
    """

    kwargs = _get_kwargs(
        id=id,
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    id: str,
    *,
    client: AuthenticatedClient,
    body: CredentialRenameRequest,
    x_csrf_token: str,
) -> Credential | Error | None:
    """Rename a passkey

    Args:
        id (str):
        x_csrf_token (str):
        body (CredentialRenameRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Credential | Error
    """

    return sync_detailed(
        id=id,
        client=client,
        body=body,
        x_csrf_token=x_csrf_token,
    ).parsed


async def asyncio_detailed(
    id: str,
    *,
    client: AuthenticatedClient,
    body: CredentialRenameRequest,
    x_csrf_token: str,
) -> Response[Credential | Error]:
    """Rename a passkey

    Args:
        id (str):
        x_csrf_token (str):
        body (CredentialRenameRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Credential | Error]
    """

    kwargs = _get_kwargs(
        id=id,
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    id: str,
    *,
    client: AuthenticatedClient,
    body: CredentialRenameRequest,
    x_csrf_token: str,
) -> Credential | Error | None:
    """Rename a passkey

    Args:
        id (str):
        x_csrf_token (str):
        body (CredentialRenameRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Credential | Error
    """

    return (
        await asyncio_detailed(
            id=id,
            client=client,
            body=body,
            x_csrf_token=x_csrf_token,
        )
    ).parsed
