# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.create_token_request import CreateTokenRequest
from ...models.error import Error
from ...models.token_with_value import TokenWithValue
from ...types import Response


def _get_kwargs(
    *,
    body: CreateTokenRequest,
    x_csrf_token: str,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    headers["X-CSRF-Token"] = x_csrf_token

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/tokens",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | TokenWithValue | None:
    if response.status_code == 201:
        response_201 = TokenWithValue.from_dict(response.json())

        return response_201

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | TokenWithValue]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: CreateTokenRequest,
    x_csrf_token: str,
) -> Response[Error | TokenWithValue]:
    """Create a write bearer token

     Issues a new write-path bearer token, owned by the admin account
    that created it. The raw token value is returned here only - it
    is never recoverable again once this response is read, the same
    as a token issued via the `token` CLI command.

    Args:
        x_csrf_token (str):
        body (CreateTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | TokenWithValue]
    """

    kwargs = _get_kwargs(
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: CreateTokenRequest,
    x_csrf_token: str,
) -> Error | TokenWithValue | None:
    """Create a write bearer token

     Issues a new write-path bearer token, owned by the admin account
    that created it. The raw token value is returned here only - it
    is never recoverable again once this response is read, the same
    as a token issued via the `token` CLI command.

    Args:
        x_csrf_token (str):
        body (CreateTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | TokenWithValue
    """

    return sync_detailed(
        client=client,
        body=body,
        x_csrf_token=x_csrf_token,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: CreateTokenRequest,
    x_csrf_token: str,
) -> Response[Error | TokenWithValue]:
    """Create a write bearer token

     Issues a new write-path bearer token, owned by the admin account
    that created it. The raw token value is returned here only - it
    is never recoverable again once this response is read, the same
    as a token issued via the `token` CLI command.

    Args:
        x_csrf_token (str):
        body (CreateTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | TokenWithValue]
    """

    kwargs = _get_kwargs(
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: CreateTokenRequest,
    x_csrf_token: str,
) -> Error | TokenWithValue | None:
    """Create a write bearer token

     Issues a new write-path bearer token, owned by the admin account
    that created it. The raw token value is returned here only - it
    is never recoverable again once this response is read, the same
    as a token issued via the `token` CLI command.

    Args:
        x_csrf_token (str):
        body (CreateTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | TokenWithValue
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
            x_csrf_token=x_csrf_token,
        )
    ).parsed
