# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.consumer_token_with_value import ConsumerTokenWithValue
from ...models.create_consumer_token_request import CreateConsumerTokenRequest
from ...models.error import Error
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    body: CreateConsumerTokenRequest,
    x_csrf_token: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_csrf_token, Unset):
        headers["X-CSRF-Token"] = x_csrf_token

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/consumer-tokens",
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> ConsumerTokenWithValue | Error | None:
    if response.status_code == 201:
        response_201 = ConsumerTokenWithValue.from_dict(response.json())

        return response_201

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 422:
        response_422 = Error.from_dict(response.json())

        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[ConsumerTokenWithValue | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient,
    body: CreateConsumerTokenRequest,
    x_csrf_token: str | Unset = UNSET,
) -> Response[ConsumerTokenWithValue | Error]:
    """Create a consumer read token

     Issues a new read token scoped to one consumer name. The raw
    token value is returned here only - it is never recoverable
    again once this response is read. A write bearer token may mint
    one too, not only an admin session - a narrowing delegation,
    since the resulting token can only ever read as far as its one
    bound consumer, never as far as the write token that issued it
    (alrayyes/hush-hush#467). A session-authenticated call needs its
    CSRF token too; a bearer-token-authenticated one doesn't, since
    there's no session to have one.

    Args:
        x_csrf_token (str | Unset):
        body (CreateConsumerTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ConsumerTokenWithValue | Error]
    """

    kwargs = _get_kwargs(
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient,
    body: CreateConsumerTokenRequest,
    x_csrf_token: str | Unset = UNSET,
) -> ConsumerTokenWithValue | Error | None:
    """Create a consumer read token

     Issues a new read token scoped to one consumer name. The raw
    token value is returned here only - it is never recoverable
    again once this response is read. A write bearer token may mint
    one too, not only an admin session - a narrowing delegation,
    since the resulting token can only ever read as far as its one
    bound consumer, never as far as the write token that issued it
    (alrayyes/hush-hush#467). A session-authenticated call needs its
    CSRF token too; a bearer-token-authenticated one doesn't, since
    there's no session to have one.

    Args:
        x_csrf_token (str | Unset):
        body (CreateConsumerTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ConsumerTokenWithValue | Error
    """

    return sync_detailed(
        client=client,
        body=body,
        x_csrf_token=x_csrf_token,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient,
    body: CreateConsumerTokenRequest,
    x_csrf_token: str | Unset = UNSET,
) -> Response[ConsumerTokenWithValue | Error]:
    """Create a consumer read token

     Issues a new read token scoped to one consumer name. The raw
    token value is returned here only - it is never recoverable
    again once this response is read. A write bearer token may mint
    one too, not only an admin session - a narrowing delegation,
    since the resulting token can only ever read as far as its one
    bound consumer, never as far as the write token that issued it
    (alrayyes/hush-hush#467). A session-authenticated call needs its
    CSRF token too; a bearer-token-authenticated one doesn't, since
    there's no session to have one.

    Args:
        x_csrf_token (str | Unset):
        body (CreateConsumerTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ConsumerTokenWithValue | Error]
    """

    kwargs = _get_kwargs(
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient,
    body: CreateConsumerTokenRequest,
    x_csrf_token: str | Unset = UNSET,
) -> ConsumerTokenWithValue | Error | None:
    """Create a consumer read token

     Issues a new read token scoped to one consumer name. The raw
    token value is returned here only - it is never recoverable
    again once this response is read. A write bearer token may mint
    one too, not only an admin session - a narrowing delegation,
    since the resulting token can only ever read as far as its one
    bound consumer, never as far as the write token that issued it
    (alrayyes/hush-hush#467). A session-authenticated call needs its
    CSRF token too; a bearer-token-authenticated one doesn't, since
    there's no session to have one.

    Args:
        x_csrf_token (str | Unset):
        body (CreateConsumerTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ConsumerTokenWithValue | Error
    """

    return (
        await asyncio_detailed(
            client=client,
            body=body,
            x_csrf_token=x_csrf_token,
        )
    ).parsed
