# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any, cast
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...types import Response


def _get_kwargs(
    id: str,
    *,
    x_csrf_token: str,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    headers["X-CSRF-Token"] = x_csrf_token

    _kwargs: dict[str, Any] = {
        "method": "delete",
        "url": "/tokens/{id}/purge".format(
            id=quote(str(id), safe=""),
        ),
    }

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Any | Error | None:
    if response.status_code == 204:
        response_204 = cast(Any, None)
        return response_204

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 409:
        response_409 = Error.from_dict(response.json())

        return response_409

    if response.status_code == 422:
        response_422 = Error.from_dict(response.json())

        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Any | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    id: str,
    *,
    client: AuthenticatedClient,
    x_csrf_token: str,
) -> Response[Any | Error]:
    """Permanently delete a dead write bearer token

     Permanently removes the token issued under id, once it's already
    revoked or past its expiry - `revokeToken`'s soft-delete stays the
    only way to invalidate a still-active token. Unlike `revokeToken`,
    an audit-log entry attributed to a purged token's id no longer
    resolves to a description or owner afterward - the accepted
    tradeoff for actually removing it.

    Args:
        id (str):
        x_csrf_token (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | Error]
    """

    kwargs = _get_kwargs(
        id=id,
        x_csrf_token=x_csrf_token,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    id: str,
    *,
    client: AuthenticatedClient,
    x_csrf_token: str,
) -> Any | Error | None:
    """Permanently delete a dead write bearer token

     Permanently removes the token issued under id, once it's already
    revoked or past its expiry - `revokeToken`'s soft-delete stays the
    only way to invalidate a still-active token. Unlike `revokeToken`,
    an audit-log entry attributed to a purged token's id no longer
    resolves to a description or owner afterward - the accepted
    tradeoff for actually removing it.

    Args:
        id (str):
        x_csrf_token (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | Error
    """

    return sync_detailed(
        id=id,
        client=client,
        x_csrf_token=x_csrf_token,
    ).parsed


async def asyncio_detailed(
    id: str,
    *,
    client: AuthenticatedClient,
    x_csrf_token: str,
) -> Response[Any | Error]:
    """Permanently delete a dead write bearer token

     Permanently removes the token issued under id, once it's already
    revoked or past its expiry - `revokeToken`'s soft-delete stays the
    only way to invalidate a still-active token. Unlike `revokeToken`,
    an audit-log entry attributed to a purged token's id no longer
    resolves to a description or owner afterward - the accepted
    tradeoff for actually removing it.

    Args:
        id (str):
        x_csrf_token (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Any | Error]
    """

    kwargs = _get_kwargs(
        id=id,
        x_csrf_token=x_csrf_token,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    id: str,
    *,
    client: AuthenticatedClient,
    x_csrf_token: str,
) -> Any | Error | None:
    """Permanently delete a dead write bearer token

     Permanently removes the token issued under id, once it's already
    revoked or past its expiry - `revokeToken`'s soft-delete stays the
    only way to invalidate a still-active token. Unlike `revokeToken`,
    an audit-log entry attributed to a purged token's id no longer
    resolves to a description or owner afterward - the accepted
    tradeoff for actually removing it.

    Args:
        id (str):
        x_csrf_token (str):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Any | Error
    """

    return (
        await asyncio_detailed(
            id=id,
            client=client,
            x_csrf_token=x_csrf_token,
        )
    ).parsed
