# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.consumer_token_with_value import ConsumerTokenWithValue
from ...models.error import Error
from ...models.rotate_consumer_token_request import RotateConsumerTokenRequest
from ...types import UNSET, Response, Unset


def _get_kwargs(
    id: str,
    *,
    body: RotateConsumerTokenRequest,
    x_csrf_token: str | Unset = UNSET,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    if not isinstance(x_csrf_token, Unset):
        headers["X-CSRF-Token"] = x_csrf_token

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/consumer-tokens/{id}/rotate".format(
            id=quote(str(id), safe=""),
        ),
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> ConsumerTokenWithValue | Error | None:
    if response.status_code == 200:
        response_200 = ConsumerTokenWithValue.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 422:
        response_422 = Error.from_dict(response.json())

        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[ConsumerTokenWithValue | Error]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    id: str,
    *,
    client: AuthenticatedClient,
    body: RotateConsumerTokenRequest,
    x_csrf_token: str | Unset = UNSET,
) -> Response[ConsumerTokenWithValue | Error]:
    """Rotate a consumer read token

     Replaces the secret and expiry of the consumer token issued under
    id, keeping its id, consumer, and description unchanged. The old
    secret stops authenticating immediately. The new raw token value
    is returned here only, the same as `createConsumerToken`.

    Unlike `revokeConsumerToken`, an id that's unknown, already
    revoked, or already expired is an error: a rotate response
    promises the caller a working new secret, and there's no valid
    token to hand one to. A write bearer token may rotate one too,
    the same as it may create one (alrayyes/hush-hush#467).

    Args:
        id (str):
        x_csrf_token (str | Unset):
        body (RotateConsumerTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ConsumerTokenWithValue | Error]
    """

    kwargs = _get_kwargs(
        id=id,
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    id: str,
    *,
    client: AuthenticatedClient,
    body: RotateConsumerTokenRequest,
    x_csrf_token: str | Unset = UNSET,
) -> ConsumerTokenWithValue | Error | None:
    """Rotate a consumer read token

     Replaces the secret and expiry of the consumer token issued under
    id, keeping its id, consumer, and description unchanged. The old
    secret stops authenticating immediately. The new raw token value
    is returned here only, the same as `createConsumerToken`.

    Unlike `revokeConsumerToken`, an id that's unknown, already
    revoked, or already expired is an error: a rotate response
    promises the caller a working new secret, and there's no valid
    token to hand one to. A write bearer token may rotate one too,
    the same as it may create one (alrayyes/hush-hush#467).

    Args:
        id (str):
        x_csrf_token (str | Unset):
        body (RotateConsumerTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ConsumerTokenWithValue | Error
    """

    return sync_detailed(
        id=id,
        client=client,
        body=body,
        x_csrf_token=x_csrf_token,
    ).parsed


async def asyncio_detailed(
    id: str,
    *,
    client: AuthenticatedClient,
    body: RotateConsumerTokenRequest,
    x_csrf_token: str | Unset = UNSET,
) -> Response[ConsumerTokenWithValue | Error]:
    """Rotate a consumer read token

     Replaces the secret and expiry of the consumer token issued under
    id, keeping its id, consumer, and description unchanged. The old
    secret stops authenticating immediately. The new raw token value
    is returned here only, the same as `createConsumerToken`.

    Unlike `revokeConsumerToken`, an id that's unknown, already
    revoked, or already expired is an error: a rotate response
    promises the caller a working new secret, and there's no valid
    token to hand one to. A write bearer token may rotate one too,
    the same as it may create one (alrayyes/hush-hush#467).

    Args:
        id (str):
        x_csrf_token (str | Unset):
        body (RotateConsumerTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[ConsumerTokenWithValue | Error]
    """

    kwargs = _get_kwargs(
        id=id,
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    id: str,
    *,
    client: AuthenticatedClient,
    body: RotateConsumerTokenRequest,
    x_csrf_token: str | Unset = UNSET,
) -> ConsumerTokenWithValue | Error | None:
    """Rotate a consumer read token

     Replaces the secret and expiry of the consumer token issued under
    id, keeping its id, consumer, and description unchanged. The old
    secret stops authenticating immediately. The new raw token value
    is returned here only, the same as `createConsumerToken`.

    Unlike `revokeConsumerToken`, an id that's unknown, already
    revoked, or already expired is an error: a rotate response
    promises the caller a working new secret, and there's no valid
    token to hand one to. A write bearer token may rotate one too,
    the same as it may create one (alrayyes/hush-hush#467).

    Args:
        id (str):
        x_csrf_token (str | Unset):
        body (RotateConsumerTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        ConsumerTokenWithValue | Error
    """

    return (
        await asyncio_detailed(
            id=id,
            client=client,
            body=body,
            x_csrf_token=x_csrf_token,
        )
    ).parsed
