# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

from http import HTTPStatus
from typing import Any
from urllib.parse import quote

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.error import Error
from ...models.rotate_token_request import RotateTokenRequest
from ...models.token_with_value import TokenWithValue
from ...types import Response


def _get_kwargs(
    id: str,
    *,
    body: RotateTokenRequest,
    x_csrf_token: str,
) -> dict[str, Any]:
    headers: dict[str, Any] = {}
    headers["X-CSRF-Token"] = x_csrf_token

    _kwargs: dict[str, Any] = {
        "method": "post",
        "url": "/tokens/{id}/rotate".format(
            id=quote(str(id), safe=""),
        ),
    }

    _kwargs["json"] = body.to_dict()

    headers["Content-Type"] = "application/json"

    _kwargs["headers"] = headers
    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Error | TokenWithValue | None:
    if response.status_code == 200:
        response_200 = TokenWithValue.from_dict(response.json())

        return response_200

    if response.status_code == 400:
        response_400 = Error.from_dict(response.json())

        return response_400

    if response.status_code == 401:
        response_401 = Error.from_dict(response.json())

        return response_401

    if response.status_code == 404:
        response_404 = Error.from_dict(response.json())

        return response_404

    if response.status_code == 422:
        response_422 = Error.from_dict(response.json())

        return response_422

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[Error | TokenWithValue]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    id: str,
    *,
    client: AuthenticatedClient,
    body: RotateTokenRequest,
    x_csrf_token: str,
) -> Response[Error | TokenWithValue]:
    """Rotate a write bearer token

     Replaces the secret and expiry of the token issued under id,
    keeping its id, description, and owner unchanged - so an audit
    log entry, or anything else that already refers to the token by
    id, keeps resolving through the rotation. The old secret stops
    authenticating immediately. The new raw token value is returned
    here only, the same as `createToken`.

    Unlike `revokeToken`, an id that's unknown, already revoked, or
    already expired is an error: a rotate response promises the
    caller a working new secret, and there's no valid token to hand
    one to.

    Args:
        id (str):
        x_csrf_token (str):
        body (RotateTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | TokenWithValue]
    """

    kwargs = _get_kwargs(
        id=id,
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    id: str,
    *,
    client: AuthenticatedClient,
    body: RotateTokenRequest,
    x_csrf_token: str,
) -> Error | TokenWithValue | None:
    """Rotate a write bearer token

     Replaces the secret and expiry of the token issued under id,
    keeping its id, description, and owner unchanged - so an audit
    log entry, or anything else that already refers to the token by
    id, keeps resolving through the rotation. The old secret stops
    authenticating immediately. The new raw token value is returned
    here only, the same as `createToken`.

    Unlike `revokeToken`, an id that's unknown, already revoked, or
    already expired is an error: a rotate response promises the
    caller a working new secret, and there's no valid token to hand
    one to.

    Args:
        id (str):
        x_csrf_token (str):
        body (RotateTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | TokenWithValue
    """

    return sync_detailed(
        id=id,
        client=client,
        body=body,
        x_csrf_token=x_csrf_token,
    ).parsed


async def asyncio_detailed(
    id: str,
    *,
    client: AuthenticatedClient,
    body: RotateTokenRequest,
    x_csrf_token: str,
) -> Response[Error | TokenWithValue]:
    """Rotate a write bearer token

     Replaces the secret and expiry of the token issued under id,
    keeping its id, description, and owner unchanged - so an audit
    log entry, or anything else that already refers to the token by
    id, keeps resolving through the rotation. The old secret stops
    authenticating immediately. The new raw token value is returned
    here only, the same as `createToken`.

    Unlike `revokeToken`, an id that's unknown, already revoked, or
    already expired is an error: a rotate response promises the
    caller a working new secret, and there's no valid token to hand
    one to.

    Args:
        id (str):
        x_csrf_token (str):
        body (RotateTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[Error | TokenWithValue]
    """

    kwargs = _get_kwargs(
        id=id,
        body=body,
        x_csrf_token=x_csrf_token,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    id: str,
    *,
    client: AuthenticatedClient,
    body: RotateTokenRequest,
    x_csrf_token: str,
) -> Error | TokenWithValue | None:
    """Rotate a write bearer token

     Replaces the secret and expiry of the token issued under id,
    keeping its id, description, and owner unchanged - so an audit
    log entry, or anything else that already refers to the token by
    id, keeps resolving through the rotation. The old secret stops
    authenticating immediately. The new raw token value is returned
    here only, the same as `createToken`.

    Unlike `revokeToken`, an id that's unknown, already revoked, or
    already expired is an error: a rotate response promises the
    caller a working new secret, and there's no valid token to hand
    one to.

    Args:
        id (str):
        x_csrf_token (str):
        body (RotateTokenRequest):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Error | TokenWithValue
    """

    return (
        await asyncio_detailed(
            id=id,
            client=client,
            body=body,
            x_csrf_token=x_csrf_token,
        )
    ).parsed
