# Code generated by openapi-python-client from hush-hush/api/openapi.yaml; DO NOT EDIT.

import datetime
from http import HTTPStatus
from typing import Any

import httpx

from ... import errors
from ...client import AuthenticatedClient, Client
from ...models.audit_log_entry import AuditLogEntry
from ...types import UNSET, Response, Unset


def _get_kwargs(
    *,
    object_id: str | Unset = UNSET,
    caller: str | Unset = UNSET,
    from_: datetime.datetime | Unset = UNSET,
    to: datetime.datetime | Unset = UNSET,
) -> dict[str, Any]:

    params: dict[str, Any] = {}

    params["object_id"] = object_id

    params["caller"] = caller

    json_from_: str | Unset = UNSET
    if not isinstance(from_, Unset):
        json_from_ = from_.isoformat()
    params["from"] = json_from_

    json_to: str | Unset = UNSET
    if not isinstance(to, Unset):
        json_to = to.isoformat()
    params["to"] = json_to

    params = {k: v for k, v in params.items() if v is not UNSET and v is not None}

    _kwargs: dict[str, Any] = {
        "method": "get",
        "url": "/audit-log",
        "params": params,
    }

    return _kwargs


def _parse_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> list[AuditLogEntry] | None:
    if response.status_code == 200:
        response_200 = []
        _response_200 = response.json()
        for response_200_item_data in _response_200:
            response_200_item = AuditLogEntry.from_dict(response_200_item_data)

            response_200.append(response_200_item)

        return response_200

    if client.raise_on_unexpected_status:
        raise errors.UnexpectedStatus(response.status_code, response.content)
    else:
        return None


def _build_response(
    *, client: AuthenticatedClient | Client, response: httpx.Response
) -> Response[list[AuditLogEntry]]:
    return Response(
        status_code=HTTPStatus(response.status_code),
        content=response.content,
        headers=response.headers,
        parsed=_parse_response(client=client, response=response),
    )


def sync_detailed(
    *,
    client: AuthenticatedClient | Client,
    object_id: str | Unset = UNSET,
    caller: str | Unset = UNSET,
    from_: datetime.datetime | Unset = UNSET,
    to: datetime.datetime | Unset = UNSET,
) -> Response[list[AuditLogEntry]]:
    r"""Query the audit log

     Every create, read, update, and delete call is recorded here -
    this is what answers \"did anyone fetch this ciphertext\" during a
    rotation or incident, since v1 has no pre-fetch access check.
    Filters combine with AND when more than one is given.

    Args:
        object_id (str | Unset):
        caller (str | Unset):
        from_ (datetime.datetime | Unset):
        to (datetime.datetime | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[list[AuditLogEntry]]
    """

    kwargs = _get_kwargs(
        object_id=object_id,
        caller=caller,
        from_=from_,
        to=to,
    )

    response = client.get_httpx_client().request(
        **kwargs,
    )

    return _build_response(client=client, response=response)


def sync(
    *,
    client: AuthenticatedClient | Client,
    object_id: str | Unset = UNSET,
    caller: str | Unset = UNSET,
    from_: datetime.datetime | Unset = UNSET,
    to: datetime.datetime | Unset = UNSET,
) -> list[AuditLogEntry] | None:
    r"""Query the audit log

     Every create, read, update, and delete call is recorded here -
    this is what answers \"did anyone fetch this ciphertext\" during a
    rotation or incident, since v1 has no pre-fetch access check.
    Filters combine with AND when more than one is given.

    Args:
        object_id (str | Unset):
        caller (str | Unset):
        from_ (datetime.datetime | Unset):
        to (datetime.datetime | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        list[AuditLogEntry]
    """

    return sync_detailed(
        client=client,
        object_id=object_id,
        caller=caller,
        from_=from_,
        to=to,
    ).parsed


async def asyncio_detailed(
    *,
    client: AuthenticatedClient | Client,
    object_id: str | Unset = UNSET,
    caller: str | Unset = UNSET,
    from_: datetime.datetime | Unset = UNSET,
    to: datetime.datetime | Unset = UNSET,
) -> Response[list[AuditLogEntry]]:
    r"""Query the audit log

     Every create, read, update, and delete call is recorded here -
    this is what answers \"did anyone fetch this ciphertext\" during a
    rotation or incident, since v1 has no pre-fetch access check.
    Filters combine with AND when more than one is given.

    Args:
        object_id (str | Unset):
        caller (str | Unset):
        from_ (datetime.datetime | Unset):
        to (datetime.datetime | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        Response[list[AuditLogEntry]]
    """

    kwargs = _get_kwargs(
        object_id=object_id,
        caller=caller,
        from_=from_,
        to=to,
    )

    response = await client.get_async_httpx_client().request(**kwargs)

    return _build_response(client=client, response=response)


async def asyncio(
    *,
    client: AuthenticatedClient | Client,
    object_id: str | Unset = UNSET,
    caller: str | Unset = UNSET,
    from_: datetime.datetime | Unset = UNSET,
    to: datetime.datetime | Unset = UNSET,
) -> list[AuditLogEntry] | None:
    r"""Query the audit log

     Every create, read, update, and delete call is recorded here -
    this is what answers \"did anyone fetch this ciphertext\" during a
    rotation or incident, since v1 has no pre-fetch access check.
    Filters combine with AND when more than one is given.

    Args:
        object_id (str | Unset):
        caller (str | Unset):
        from_ (datetime.datetime | Unset):
        to (datetime.datetime | Unset):

    Raises:
        errors.UnexpectedStatus: If the server returns an undocumented status code and Client.raise_on_unexpected_status is True.
        httpx.TimeoutException: If the request takes longer than Client.timeout.

    Returns:
        list[AuditLogEntry]
    """

    return (
        await asyncio_detailed(
            client=client,
            object_id=object_id,
            caller=caller,
            from_=from_,
            to=to,
        )
    ).parsed
